export const USERPASSWORDVERIFICATION = {
  VERIFICATION_01:
    "ERM_AuthService_AuthManager_UserPasswordVerification_01".toLowerCase(),
  VERIFICATION_02:
    "ERM_AuthService_AuthManager_UserPasswordVerification_02".toLowerCase(),
  VERIFICATION_03:
    "ERM_AuthService_AuthManager_UserPasswordVerification_03".toLowerCase(),
  VERIFICATION_04:
    "ERM_AuthService_AuthManager_UserPasswordVerification_04".toLowerCase(),
  VERIFICATION_05:
    "ERM_AuthService_AuthManager_UserPasswordVerification_05".toLowerCase(),
  VERIFICATION_06:
    "ERM_AuthService_AuthManager_UserPasswordVerification_06".toLowerCase(),
  VERIFICATION_07:
    "ERM_AuthService_AuthManager_UserPasswordVerification_07".toLowerCase(),
  VERIFICATION_08:
    "ERM_AuthService_AuthManager_UserPasswordVerification_08".toLowerCase(),
  VERIFICATION_09:
    "ERM_AuthService_AuthManager_UserPasswordVerification_09".toLowerCase(),
  VERIFICATION_10:
    "ERM_AuthService_AuthManager_UserPasswordVerification_10".toLowerCase(),
  VERIFICATION_11:
    "ERM_AuthService_AuthManager_UserPasswordVerification_11".toLowerCase(),
  VERIFICATION_12:
    "ERM_AuthService_AuthManager_UserPasswordVerification_12".toLowerCase(),
  VERIFICATION_17:
    "ERM_AuthService_AuthManager_UserPasswordVerification_17".toLowerCase(),
  VERIFICATION_18:
    "ERM_AuthService_AuthManager_UserPasswordVerification_18".toLowerCase(),
  VERIFICATION_19:
    "ERM_AuthService_AuthManager_UserPasswordVerification_19".toLowerCase(),
  VERIFICATION_20:
    "ERM_AuthService_AuthManager_UserPasswordVerification_20".toLowerCase(),
  VERIFICATION_21:
    "ERM_AuthService_AuthManager_UserPasswordVerification_21".toLowerCase(),
  VERIFICATION_22:
    "ERM_AuthService_AuthManager_UserPasswordVerification_22".toLowerCase(),
  VERIFICATION_23:
    "ERM_AuthService_AuthManager_UserPasswordVerification_23".toLowerCase(),
  VERIFICATION_24:
    "ERM_AuthService_AuthManager_UserPasswordVerification_24".toLowerCase(),
  VERIFICATION_25:
    "ERM_AuthService_AuthManager_UserPasswordVerification_25".toLowerCase(),
  VERIFICATION_26:
    "ERM_AuthService_AuthManager_UserPasswordVerification_26".toLowerCase(),
  VERIFICATION_27:
    "ERM_AuthService_AuthManager_UserPasswordVerification_27".toLowerCase(),
  VERIFICATION_28:
    "ERM_AuthService_AuthManager_UserPasswordVerification_28".toLowerCase(),
  VERIFICATION_29:
    "ERM_AuthService_AuthManager_UserPasswordVerification_29".toLowerCase(),
  VERIFICATION_30:
    "ERM_AuthService_AuthManager_UserPasswordVerification_30".toLowerCase(),
  VERIFICATION_31:
    "ERM_AuthService_AuthManager_UserPasswordVerification_31".toLowerCase(),
  VERIFICATION_32:
    "ERM_AuthService_AuthManager_UserPasswordVerification_32".toLowerCase(),
  VERIFICATION_33:
    "ERM_AuthService_AuthManager_UserPasswordVerification_33".toLowerCase(),
  VERIFICATION_34:
    "ERM_AuthService_AuthManager_UserPasswordVerification_34".toLowerCase(),
  VERIFICATION_35:
    "ERM_AuthService_AuthManager_UserPasswordVerification_35".toLowerCase(),
  VERIFICATION_36:
    "ERM_AuthService_AuthManager_UserPasswordVerification_36".toLowerCase(),
  VERIFICATION_37:
    "ERM_AuthService_AuthManager_UserPasswordVerification_37".toLowerCase(),
  VERIFICATION_38:
    "ERM_AuthService_AuthManager_UserPasswordVerification_38".toLowerCase(),
  VERIFICATION_39:
    "ERM_AuthService_AuthManager_UserPasswordVerification_39".toLowerCase(),
  // Add more as needed
};

export const USERSPASSWORDCREATION = {
  CREATION_01:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_01".toLowerCase(),
  CREATION_02:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_02".toLowerCase(),
  CREATION_03:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_03".toLowerCase(),
  CREATION_04:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_04".toLowerCase(),
  CREATION_05:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_05".toLowerCase(),
  CREATION_06:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_06".toLowerCase(),
  CREATION_07:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_07".toLowerCase(),
  CREATION_08:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_08".toLowerCase(),
  CREATION_09:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_09".toLowerCase(),
  CREATION_10:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_10".toLowerCase(),
  CREATION_11:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_11".toLowerCase(),
  CREATION_12:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_12".toLowerCase(),
  CREATION_13:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_13".toLowerCase(),
  CREATION_14:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_14".toLowerCase(),
  CREATION_15:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_15".toLowerCase(),
  CREATION_16:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_16".toLowerCase(),
  CREATION_17:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_17".toLowerCase(),
  CREATION_18:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_18".toLowerCase(),
  CREATION_19:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_19".toLowerCase(),
  CREATION_20:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_20".toLowerCase(),
  CREATION_21:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_21".toLowerCase(),
  CREATION_22:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_22".toLowerCase(),
  CREATION_23:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_23".toLowerCase(),
  CREATION_24:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_24".toLowerCase(),
  CREATION_25:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_25".toLowerCase(),
  CREATION_26:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_26".toLowerCase(),
  CREATION_27:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_27".toLowerCase(),
  CREATION_28:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_28".toLowerCase(),
  CREATION_29:
    "ERM_AuthService_SignUpManager_UsersPasswordCreation_29".toLowerCase(),
  // Add more as needed
};
