//For Authentication api's

//  For LOADER
export const LOADER = "LOADER"

//for signup
export const SIGN_UP_INIT = "SIGN_UP_INIT"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_FAIL = "SIGN_UP_FAIL"

//for login
export const SIGN_IN_INIT = "SIGN_IN_INIT"
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS"
export const SIGN_IN_FAIL = "SIGN_IN_FAIL"

//for forgot password
export const FORGOT_PASSWORD_INIT = "FORGOTPASSWORD_IN_INIT"
export const FORGOT_PASSWORD_SUCCESS = "FORGOTPASSWORD_IN_SUCCESS"
export const FORGOT_PASSWORD_FAIL = "FORGOTPASSWORD_IN_FAIL"

//for opt verification
export const VERIFY_OPT_INIT = "VERIFY_IN_INIT"
export const VERIFY_OPT_SUCCESS = "VERIFY_OPT_SUCCESS"
export const VERIFY_OPT_FAIL = "VERIFY_OPT_FAIL"

export const VERIFY_OTPSIGNUP_SUCCESS = "VERIFY_OTPSIGNUP_SUCCESS"
export const VERIFY_OTPSIGNUP_FAIL = "VERIFY_OTPSIGNUP_FAIL"

export const RESEND_OTP_INIT = "RESEND_OTP_INIT"
export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS"
export const RESEND_OTP_FAIL = "RESEND_OTP_FAIL"

export const RESEND_OTP_FORGOTPASSWORD_SUCCESS =
  "RESEND_OTP_FORGOTPASSWORD_SUCCESS"
export const RESEND_OTP_FORGOTPASSWORD_FAIL = "RESEND_OTP_FORGOTPASSWORD_FAIL"

// for change password
export const CHANGE_PASSWORD_INIT = "CHANGE_PASSWORD_INIT"
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL"

//for signout
export const SIGN_OUT = "SIGN_OUT"

//Refresh token
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS"
export const REFRESH_TOKEN_FAIL = "REFRESH_TOKEN_FAIL"

//Clear State Back Button
export const CLEAR_STATE_BACK = "CLEAR_STATE_BACK"

//TodoList
export const SHOW = "SHOW"
export const SET_LOADER_FALSE = "SET_LOADER_FALSE"
export const GET_TODOLIST_LOADER_START = "GET_TODOLIST_LOADER_START"
export const GET_TODO_FAIL = "GET_TODO_FAIL"

//Upload
export const GET_UPLOAD_FAIL = "GET_UPLOAD_FAIL"
export const GET_UPLOAD_LOADER_START = "GET_UPLOAD_LOADER_START"
export const SET_LOADER_FALSE_UPLOAD = "SET_LOADER_FALSE_UPLOAD"
export const UPLOAD_DOCUMNET_FILE_SUCCESS = "UPLOAD_DOCUMNET_FILE_SUCCESS"
export const UPLOAD_DOCUMNET_FILE_FAIL = "UPLOAD_DOCUMNET_FILE_FAIL"
export const GET_ALL_ASSIGNEES_SUCCESS = "GET_ALL_ASSIGNEES_SUCCESS"
export const GET_ALL_ASSIGNEES_FAIL = "GET_ALL_ASSIGNEES_FAIL"

// ali
//for Gell All Settings
export const GETSETTING_INIT = "SETTINGS_INIT"
export const GETSETTING_SUCCESS = "SETTING_SUCCESS"
export const GETSETTING_FAIL = "SETTING_FAIL"

//FOR UPDATE USER PROFILE
export const UPDATEUSERPROFILE_INIT = "UPDATEUSERPROFILE_INIT"
export const UPDATEUSERPROFILE_SUCCESS = "UPDATEUSERPROFILE_SUCCESS"
export const UPDATEUSERPROFILE_FAIL = "UPDATEUSERPROFILE_FAIL"

// FOR UPDATE USER NOTIFCATION
export const UPDATEUSERNOTIFICATION_INIT = "UPDATEUSERNOTIFICATION_INIT"
export const UPDATEUSERNOTIFICATION_SUCCESS = "UPDATEUSERNOTIFICATION_SUCCESS"
export const UPDATEUSERNOTIFICATION_FAIL = "UPDATEUSERNOTIFICATION_FAIL"

//FOR UPDATE USER GENERAL SETTING
export const UPDATEUSERGENERALSETTING_INIT = "UPDATEUSERGENERALSETTING_INIT"
export const UPDATEUSERGENERALSETTING_SUCCESS =
  "UPDATEUSERGENERALSETTING_SUCCESS"
export const UPDATEUSERGENERALSETTING_FAIL = "UPDATEUSERGENERALSETTING_FAIL"

//FOR GETTING USER NOTIFICATION
export const GETUSERNOTIFICATION_INIT = "GETUSERNOTIFICATION_INIT"
export const GETUSERNOTIFICATION_SUCCESS = "GETUSERNOTIFICATION_SUCCESS"
export const GETUSERNOTIFICATION_FAIL = "GETUSERNOTIFICATION_FAIL"
// aun
//For FAQ's
export const GET_FAQS_INIT = "GET_FAQS_INIT"
export const GET_FAQS_SUCCESS = "GET_FAQS_SUCCESS"
export const GET_FAQS_FAIL = "GET_FAQS_FAIL"

// For COUNTRY CODES
export const GET_COUNTRYCODE_INIT = "GET_COUNTRYCODE_INIT"
export const GET_COUNTRYCODE_SUCCESS = "GET_COUNTRYCODE_SUCCESS"
export const GET_COUNTRYCODE_FAIL = "GET_COUNTRYCODE_FAIL"

// FOR TIME ZONES
export const GET_TIMEZONE_INIT = "GET_TIMEZONE_INIT"
export const GET_TIMEZONE_SUCCESS = "GET_TIMEZONE_SUCCESS"
export const GET_TIMEZONE_FAIL = "GET_TIMEZONE_FAIL"

//aun
//For GetMeetingByUserID
export const GET_MEETINGUSERID_INIT = "GET_MEETINGUSERID_INIT"
export const GET_MEETINGUSERID_SUCCESS = "GET_MEETINGUSERID_SUCCESS"
export const GET_MEETINGUSERID_FAIL = "GET_MEETINGUSERID_FAIL"
export const SEARCH_MEETING_RESPONSE = "SEARCH_MEETING_RESPONSE"

//aun
//Get todolist User id
export const GET_TODOLIST_INIT = " GET_TODOLIST_INIT"
export const GET_TODOLIST_SUCCESS = " GET_TODOLIST_SUCCESS"
export const GET_TODOLIST_FAIL = " GET_TODOLIST_FAIL"

// FOR ASSIGNEES LIST
export const ASSIGNESS_LIST_INIT = "ASSIGNESS_LIST_INIT"
export const ASSIGNESS_LIST_SUCCESS = "ASSIGNESS_LIST_SUCCESS"
export const ASSIGNESS_LIST_FAIL = "ASSIGNESS_LIST_FAIL"

//SCHEDULE MEETING
export const SCHEDULE_NEW_MEETING_INIT = "SCHEDULE_NEW_MEETING_INIT"
export const SCHEDULE_NEW_MEETING_FAIL = "SCHEDULE_NEW_MEETING_FAIL"

//VIEW MEETING
export const VIEW_MEETING_INIT = "VIEW_MEETING_INIT"
export const VIEW_MEETING_SUCESS = "VIEW_MEETING_SUCESS"
export const VIEW_MEETING_FAIL = "VIEW_MEETING_FAIL"

// CLEARE STATE OF ASSIGNEES LIST STATES
export const CLEARE_STATE = "CLEARE_STATE"
export const VIEW_TODO_SUCCESS = "VIEW_TODO_SUCCESS"
export const VIEW_TODO_FAIL = "VIEW_TODO_FAIL"

export const CLEAR_STATE = "CLEAR_STATE"
export const CLEAR_RESPONSE_MESSAGE = "CLEAR_RESPONSE_MESSAGE"

export const CANCEL_MEETING_INIT = "CANCEL_MEETING_INIT"
export const CANCEL_MEETING_SUCCESS = "CANCEL_MEETING_SUCCESS"
export const CANCEL_MEETING_FAIL = "CANCEL_MEETING_FAIL"

export const START_MEETING_INIT = "START_MEETING_INIT"
export const START_MEETING_SUCCESS = "START_MEETING_SUCCESS"
export const START_MEETING_FAIL = "START_MEETING_FAIL"

export const END_MEETING_INIT = "END_MEETING_INIT"
export const END_MEETING_SUCCESS = "END_MEETING_SUCCESS"
export const END_MEETING_FAIL = "END_MEETING_FAIL"

// GET CALENDAR DATA
export const GET_DATA_FOR_CALENDAR_INIT = "GET_DATA_FOR_CALENDAR_INIT"
export const GET_DATA_FOR_CALENDAR_SUCCESS = "GET_DATA_FOR_CALENDAR_SUCCESS"
export const GET_DATA_FOR_CALENDAR_FAIL = "GET_DATA_FOR_CALENDAR_FAIL"

// MAINTAIN STATES FOR ONBOARDS

export const SHOW_MODAL_STATE = "SHOW_MODAL_STATE"
export const ISDETAIL_MODAL_STATE = "ISDETAIL_MODAL_STATE"
export const ISAGENDA_MODAL_STATE = "ISAGENDA_MODAL_STATE"
export const ISATTENDEES_MODAL_STATE = "ISATTENDEES_MODAL_STATE"
export const STEPS_MODAL_STATE = "STEPS_MODAL_STATE"

// GET TODOS STATUS
export const GET_TODOSSTATUS_INIT = "GET_TODOSSTATUS_INIT"
export const GET_TODOSSTATUS_SUCCESS = "GET_TODOSSTATUS_SUCCESS"
export const GET_TODOSSTATUS_FAIL = "GET_TODOSSTATUS_FAIL"

// UPDATE TODOS STATUS
export const UPDATE_TODOSTATUS_INIT = "UPDATE_TODOSTATUS_INIT"
export const UPDATE_TODOSTATUS_SUCCESS = "UPDATE_TODOSTATUS_SUCCESS"
export const UPDATE_TODOSTATUS_FAIL = "UPDATE_TODOSTATUS_FAIL"

//Download
export const GET_DOWNLOAD_FAIL = "GET_DOWNLOAD_FAIL"
export const GET_DOWNLOAD_LOADER_START = "GET_DOWNLOAD_LOADER_START"
export const SET_LOADER_FALSE_DOWNLOAD = "SET_LOADER_FALSE_DOWNLOAD"
export const DOWNLOAD_DOCUMENT_FILE_SUCCESS = "DOWNLOAD_DOCUMENT_FILE_SUCCESS"
export const DOWNLOAD_DOCUMENT_FILE_FAIL = "DOWNLOAD_DOCUMENT_FILE_FAIL"

export const RESET_ALL_FILES_UPLOAD = "RESET_ALL_FILES_UPLOAD"

// POST ASSGINEEE COMMENTS IN TODOVIEW
export const POST_ASSIGNEEECOMMENTS_INIT = "POST_ASSIGNEEECOMMENTS_INIT"
export const POST_ASSIGNEEECOMMENTS_SUCCESS = "POST_ASSIGNEEECOMMENTS_SUCCESS"
export const POST_ASSIGNEEECOMMENTS_FAIL = "POST_ASSIGNEEECOMMENTS_FAIL"

export const SET_LOADER_TRUE = "SET_LOADER_TRUE"

export const GET_MEETINGCOUNT_SUCCESS = "GET_MEETINGCOUNT_SUCCESS"
export const GET_MEETINGCOUNT_FAIL = "GET_MEETINGCOUNT_FAIL"

export const GET_UPCOMINGEVENTS_SUCCESS = "GET_UPCOMINGEVENTS_SUCCESS"
export const GET_UPCOMINGEVENTS_FAIL = "GET_UPCOMINGEVENTS_FAIL"

export const GET_TODOCOUNT_SUCCESS = "GET_TODOCOUNT_SUCCESS"
export const GET_TODOCOUNT_FAIL = "GET_TODOCOUNT_FAIL"

export const SET_SPINNER_TRUE = "SET_SPINNER_TRUE"
export const SET_SPINNER_FALSE = "SET_SPINNER_FALSE"

export const SET_TABLESPINNER_FALSE = "SET_TABLESPINNER_FALSE"

export const HIDE = "HIDE"

//SHOW VIDEO CHAT COMPONENTS
export const SHOW_ATTACHMENTS_STATE = "SHOW_ATTACHMENTS_STATE"
export const SHOW_MINUTES_STATE = "SHOW_MINUTES_STATE"

// SHOW HID MEETING AGENDA MODAL IN VIDEO CALL
export const MEETINGATTACHMENT_MODAL = "MEETINGATTACHMENT_MODAL"

// GET MEETING AGENDAS
export const GET_MEETINGAGENDAS_INIT = "GET_MEETINGAGENDAS_INIT"
export const GET_MEETINGAGENDAS_SUCCESS = "GET_MEETINGAGENDAS_SUCCESS"
export const GET_MEETINGAGENDAS_FAIL = "GET_MEETINGAGENDAS_FAIL"

// GET MEEETING ATTACHMENTS
export const GET_ATTACHMENTSBYMEETINGID_INIT = "GET_ATTACHMENTSBYMEETINGID_INIT"
export const GET_ATTACHMENTSBYMEETINGID_SUCCESS =
  "GET_ATTACHMENTSBYMEETINGID_SUCCESS"
export const GET_ATTACHMENTSBYMEETINGID_FAIL = "GET_ATTACHMENTSBYMEETINGID_FAIL"

// GET AGENDA ATTACHMENT UPDATES
export const AGENDA_ATTACHMENTUPDATE_INIT = "AGENDA_ATTACHMENTUPDATE_INIT"
export const AGENDA_ATTACHMENTUPDATE_SUCCESS = "AGENDA_ATTACHMENTUPDATE_SUCCESS"
export const AGENDA_ATTACHMENTUPDATE_FAIL = "AGENDA_ATTACHMENTUPDATE_FAIL"

export const UPDATE_MINUTESOFMEETING_INIT = "UPDATE_MINUTESOFMEETING_INIT"
export const UPDATE_MINUTESOFMEETING_SUCCESS = "UPDATE_MINUTESOFMEETING_SUCCESS"
export const UPDATE_MINUTESOFMEETING_FAIL = "UPDATE_MINUTESOFMEETING_FAIL"

export const ADD_MINUTESOFMEETING_INIT = "UPDATE_MINUTESOFMEETING_INIT"
export const ADD_MINUTESOFMEETING_SUCCESS = "UPDATE_MINUTESOFMEETING_SUCCESS"
export const ADD_MINUTESOFMEETING_FAIL = "UPDATE_MINUTESOFMEETING_FAIL"
export const HIDEMINUTEMESSAGE = "HIDEMINUTEMESSAGE"

export const GET_REMINDERS_INIT = "GET_REMINDERS_INIT"
export const GET_REMINDERS_SUCCESS = "GET_REMINDERS_SUCCESS"
export const GET_REMINDERS_FAIL = "GET_REMINDERS_FAIL"

export const AUTH_RESPONSE_MESSAGE = "AUTH_RESPONSE_MESSAGE"
export const DOWNLOAD_RESPONSE_MESSAGE = "DOWNLOAD_RESPONSE_MESSAGE"
export const FAQS_RESPONSE_MESSAGE = "FAQS_RESPONSE_MESSAGE"
export const LISTOFASSIGNEE_RESPONSE_MESSAGE = "LISTOFASSIGNEE_RESPONSE_MESSAGE"
export const CALENDAR_RESPONSE_MESSAGE = "CALENDAR_RESPONSE_MESSAGE"
export const MEETINGID_RESPONSE_MESSAGE = "MEETINGID_RESPONSE_MESSAGE"
export const TODOS_STATUS_RESPONSE_MESSAGE = "TODOS_STATUS_RESPONSE_MESSAGE"
export const POST_ASSIGNEE_RESPONSE_MESSAGE = "POST_ASSIGNEE_RESPONSE_MESSAGE"
export const SETTING_RESPONSE_MESSAGE = "SETTING_RESPONSE_MESSAGE"
export const TODOLIST_RESPONSE_MESSAGE = "TODOLIST_RESPONSE_MESSAGE"
export const UPLOAD_RESPONSE_MESSAGE = "UPLOAD_RESPONSE_MESSAGE"
export const VIDEOCHAT_RESPONSE_MESSAGE = "VIDEOCHAT_RESPONSE_MESSAGE"

// socket update recentactivity
export const SET_RECENT_ACTIVITY_NOTIFICATION =
  "SET_RECENT_ACTIVITY_NOTIFICATION"

// action type for get tododata from socket
export const SETTODO_RECENT_ACTIVITY_DATA = "SETTODO_RECENT_ACTIVITY_DATA"
export const SET_TODO_STATUS_DATA = "SET_TODO_STATUS_DATA"

// socket Meetings
export const ALL_MEETINGS_SOCKET = "ALL_MEETINGS_SOCKET"

// socket meeting status

export const MEETING_STATUS_SOCKET = "MEETING_STATUS_SOCKET"

// For comments Socket
export const POST_COMMENTS = "POST_COMMENTS"

export const DELETE_COMMENTS = "DELETE_COMMENTS"

// Aun work on admin action types (START) //

//For Admin AddUser
export const ADMIN_ADDUSER_INIT = "ADMIN_ADDUSER_INIT"
export const ADMIN_ADDUSER_SUCCESS = "ADMIN_ADDUSER_SUCCESS"
export const ADMIN_ADDUSER_FAIL = "ADMIN_ADDUSER_FAIL"

//For Admin OrganizationUserListStatistics
export const ADMIN_USERLISTSTATIST_INIT = "ADMIN_USERLISTSTATIST_INIT"
export const ADMIN_USERLISTSTATIST_SUCCESS = "ADMIN_USERLISTSTATIST_SUCCESS"
export const ADMIN_USERLISTSTATIST_FAIL = "ADMIN_USERLISTSTATIST_FAIL"

//For Admin AllMeeting
export const ADMIN_ALLMEETING_INIT = "ADMIN_ALLMEETING_INIT"
export const ADMIN_ALLMEETING_SUCCESS = "ADMIN_ALLMEETING_SUCCESS"
export const ADMIN_ALLMEETING_FAIL = "ADMIN_ALLMEETING_FAIL"

//For Admin CancelSub
export const ADMIN_CANCELSUB_INIT = "ADMIN_CANCELSUB_INIT"
export const ADMIN_CANCELSUB_SUCCESS = "ADMIN_CANCELSUB_SUCCESS"
export const ADMIN_CANCELSUB_FAIL = "ADMIN_CANCELSUB_FAIL"

//For Admin CustomerInformation
export const ADMIN_CUSTOMERINFORMATION_INIT = "ADMIN_CUSTOMERINFORMATION_INIT"
export const ADMIN_CUSTOMERINFORMATION_SUCCESS =
  "ADMIN_CUSTOMERINFORMATION_SUCCESS"
export const ADMIN_CUSTOMERINFORMATION_FAIL = "ADMIN_CUSTOMERINFORMATION_FAIL"

// For Admin Update CustomerInformation
export const ADMIN_UPDATE_CUSTOMERINFORMATION_INIT =
  "ADMIN_UPDATE_CUSTOMERINFORMATION_INIT"
export const ADMIN_UPDATE_CUSTOMERINFORMATION_SUCCESS =
  "ADMIN_UPDATE_CUSTOMERINFORMATION_SUCCESS"
export const ADMIN_UPDATE_CUSTOMERINFORMATION_FAIL =
  "ADMIN_UPDATE_CUSTOMERINFORMATION_FAIL"

//For Admin EditUser
export const ADMIN_EDITUSER_INIT = "ADMIN_EDITUSER_INIT"
export const ADMIN_EDITUSER_SUCCESS = "ADMIN_EDITUSER_SUCCESS"
export const ADMIN_EDITUSER_FAIL = "ADMIN_EDITUSER_FAIL"

//For Admin Invoice
export const ADMIN_INVOICE_INIT = "ADMIN_INVOICE_INIT"
export const ADMIN_INVOICE_SUCCESS = "ADMIN_INVOICE_SUCCESS"
export const ADMIN_INVOICE_FAIL = "ADMIN_INVOICE_FAIL"

//For Admin Organization
export const ADMIN_ORGANIZATION_INIT = "ADMIN_ORGANIZATION_INIT"
export const ADMIN_ORGANIZATION_SUCCESS = "ADMIN_ORGANIZATION_SUCCESS"
export const ADMIN_ORGANIZATION_FAIL = "ADMIN_ORGANIZATION_FAIL"

//For Admin Email Verifiation
export const ADMIN_EMAILVARIFICATION_INIT = "ADMIN_EMAILVARIFICATION_INIT"
export const ADMIN_EMAILVARIFICATION_SUCCESS = "ADMIN_EMAILVARIFICATION_SUCCESS"
export const ADMIN_EMAILVARIFICATION_FAIL = "ADMIN_EMAILVARIFICATION_FAIL"

//For Admin PackageDetail
export const ADMIN_PACKAGEDETAIL_INIT = "ADMIN_PACKAGEDETAIL_INIT"
export const ADMIN_PACKAGEDETAIL_SUCCESS = "ADMIN_PACKAGEDETAIL_SUCCESS"
export const ADMIN_PACKAGEDETAIL_FAIL = "ADMIN_PACKAGEDETAIL_FAIL"

//For Admin PackageUpgrade
export const ADMIN_PACKAGEUPGRADE_INIT = "ADMIN_PACKAGEUPGRADE_INIT"
export const ADMIN_PACKAGEUPGRADE_SUCCESS = "ADMIN_PACKAGEUPGRADE_SUCCESS"
export const ADMIN_PACKAGEUPGRADE_FAIL = "ADMIN_PACKAGEUPGRADE_FAIL"

//For Admin PayOutstanding
export const ADMIN_PAYOUTSTANDING_INIT = "ADMIN_PAYOUTSTANDING_INIT"
export const ADMIN_PAYOUTSTANDING_SUCCESS = "ADMIN_PAYOUTSTANDING_SUCCESS"
export const ADMIN_PAYOUTSTANDING_FAIL = "ADMIN_PAYOUTSTANDING_FAIL"

//For Admin Summary
export const ADMIN_SUMMARY_INIT = "ADMIN_SUMMARY_INIT"
export const ADMIN_SUMMARY_SUCCESS = "ADMIN_SUMMARY_SUCCESS"
export const ADMIN_SUMMARY_FAIL = "ADMIN_SUMMARY_FAIL"

// Aun work on admin action types (END) //

// for organization Sign up

export const COUNTRYNAMES_INIT = "COUNTRYNAMES_INIT"
export const COUNTRYNAMES_SUCCESS = "COUNTRYNAMES_SUCCESS"
export const COUNTRYNAMES_FAIL = "COUNTRYNAMES_FAIL"

export const GETSUBSCRIPTIONPACAKGES_INIT = "GETSUBSCRIPTIONPACAKGES_INIT"
export const GETSUBSCRIPTIONPACAKGES_SUCCESS = "GETSUBSCRIPTIONPACAKGES_SUCCESS"
export const GETSUBSCRIPTIONPACAKGES_FAIL = "GETSUBSCRIPTIONPACAKGES_FAIL"

export const SIGNUPORGANIZATION_INIT = "SIGNUPORGANIZATION_INIT"
export const SIGNUPORGANIZATION_SUCCESS = "SIGNUPORGANIZATION_SUCCESS"
export const SIGNUPORGANIZATION_FAIL = "SIGNUPORGANIZATION_FAIL"

export const EMAILVALIDATION_INIT = "EMAILVALIDATION_INIT"
export const EMAILVALIDATION_SUCCESS = "EMAILVALIDATION_SUCCESS"
export const EMAILVALIDATION_FAIL = "EMAILVALIDATION_FAIL"

export const PASSWORDVALIDATION_INIT = "PASSWORDVALIDATION_INIT"
export const PASSWORDVALIDATION_SUCCESS = "PASSWORDVALIDATION_SUCCESS"
export const PASSWORDVALIDATION_FAIL = "PASSWORDVALIDATION_FAIL"

export const VERIFYOTPFOREMAIL_INIT = "VERIFYOTPFOREMAIL_INIT"
export const VERIFYOTPFOREMAIL_SUCCESS = "VERIFYOTPFOREMAIL_SUCCESS"
export const VERIFYOTPFOREMAIL_FAIL = "VERIFYOTPFOREMAIL_FAIL"

export const PASSWORDCREATION_INIT = "PASSWORDCREATION_INIT"
export const PASSWORDCREATION_SUCCESS = "PASSWORDCREATION_SUCCESS"
export const PASSWORDCREATION_FAIL = "PASSWORDCREATION_FAIL"

export const GETSELECTEDPACAKGEANDORGANIZATIONDETAILS_INIT =
  "GETSELECTEDPACAKGEANDORGANIZATIONDETAILS_INIT"
export const GETSELECTEDPACAKGEANDORGANIZATIONDETAILS_SUCCESS =
  "GETSELECTEDPACAKGEANDORGANIZATIONDETAILS_SUCCESS"
export const GETSELECTEDPACAKGEANDORGANIZATIONDETAILS_FAIL =
  "GETSELECTEDPACAKGEANDORGANIZATIONDETAILS_FAIL"

// for organization role list

export const ADMIN_ALLORGANAIZATIONROLES_INIT =
  "ADMIN_ALLORGANAIZATIONROLES_INIT"
export const ADMIN_ALLORGANAIZATIONROLES_SUCCESS =
  "ADMIN_ALLORGANAIZATIONROLES_SUCCESS"
export const ADMIN_ALLORGANAIZATIONROLES_FAIL =
  "ADMIN_ALLORGANAIZATIONROLES_FAIL"

// for user role list

export const ADMIN_USERROLELIST_INIT = "ADMIN_USERROLELIST_INIT"
export const ADMIN_USERROLELIST_SUCCESS = "ADMIN_USERROLELIST_SUCCESS"
export const ADMIN_USERROLELIST_FAIL = "ADMIN_USERROLELIST_FAIL"

// for get organization Name
export const ADMIN_GETORGANAIZATIONID_INIT = "ADMIN_GETORGANAIZATIONID_INIT"
export const ADMIN_GETORGANAIZATIONID_INIT_SUCCESS =
  "ADMIN_GETORGANAIZATIONID_INIT_SUCCESS"
export const ADMIN_GETORGANAIZATIONID_INIT_FAIL =
  "ADMIN_GETORGANAIZATIONID_INIT_FAIL"

// for get organization CLEARE MESSAGE
export const ADMIN_CLEARE_MESSAGE = "ADMIN_CLEARE_MESSAGE"

// for get All User List

export const ADMIN_ALLUSERLIST_INIT = "ADMIN_ALLUSERLIST_INIT"
export const ADMIN_ALLUSERLIST_SUCCESS = "ADMIN_ALLUSERLIST_SUCCESS"
export const ADMIN_ALLUSERLIST_FAIL = "ADMIN_ALLUSERLIST_FAIL"

// for get All User STATUS
export const ADMIN_USERSTATUSLIST_INIT = "ADMIN_USERSTATUSLIST_INIT"
export const ADMIN_USERSTATUSLIST_SUCCESS = "ADMIN_USERSTATUSLIST_SUCCESS"
export const ADMIN_USERSTATUSLIST_FAIL = "ADMIN_USERSTATUSLIST_FAIL"

// for get Edit Organization User
export const ADMIN_EDITORGANIZATIONUSER_INIT = "ADMIN_EDITORGANIZATIONUSER_INIT"
export const ADMIN_EDITORGANIZATIONUSER_SUCCESS =
  "ADMIN_EDITORGANIZATIONUSER_SUCCESS"
export const ADMIN_EDITORGANIZATIONUSER_FAIL = "ADMIN_EDITORGANIZATIONUSER_FAIL"

// for get Delete Organization User
export const ADMIN_DELETEORGANIZATIONUSER_INIT =
  "ADMIN_DELETEORGANIZATIONUSER_INIT"
export const ADMIN_DELETEORGANIZATIONUSER_SUCCESS =
  "ADMIN_DELETEORGANIZATIONUSER_SUCCESS"
export const ADMIN_DELETEORGANIZATIONUSER_FAIL =
  "ADMIN_DELETEORGANIZATIONUSER_FAIL"

export const GETPACKAGEEXPIRYDETAILS_INIT = "GETPACKAGEEXPIRYDETAILS_INIT"
export const GETPACKAGEEXPIRYDETAILS_SUCCESS = "GETPACKAGEEXPIRYDETAILS_SUCCESS"
export const GETPACKAGEEXPIRYDETAILS_FAIL = "GETPACKAGEEXPIRYDETAILS_FAIL"

export const ALLORGAINZATIONMEETING_INIT = "ALLORGAINZATIONMEETING_INIT"
export const ALLORGAINZATIONMEETING_SUCCESS = "ALLORGAINZATIONMEETING_SUCCESS"
export const ALLORGAINZATIONMEETING_FAIL = "ALLORGAINZATIONMEETING_FAIL"

export const UPDATEORGANIZTIONMEETING_INIT = "UPDATEORGANIZTIONMEETING_INIT"
export const UPDATEORGANIZTIONMEETING_SUCCESS =
  "UPDATEORGANIZTIONMEETING_SUCCESS"
export const UPDATEORGANIZTIONMEETING_FAIL = "UPDATEORGANIZTIONMEETING_FAIL"

export const DELETEORGANIZATIONMEETING_INIT = "DELETEORGANIZATION_INIT"
export const DELETEORGANIZATIONMEETING_SUCCESS = "DELETEORGANIZATION_SUCCESS"
export const DELETEORGANIZATIONMEETING_FAIL = "DELETEORGANIZATION_FAIL"

export const GETORGANIZATIONLEVELSETTING_INIT =
  "GETORGANIZATIONLEVELSETTING_INIT"
export const GETORGANIZATIONLEVELSETTING_SUCCESS =
  "GETORGANIZATIONLEVELSETTING_SUCCESS"
export const GETORGANIZATIONLEVELSETTING_FAIL =
  "GETORGANIZATIONLEVELSETTING_FAIL"

export const UPDATEORGANIZATIONLEVELSETTING_INIT =
  "UPDATEORGANIZATIONLEVELSETTING_INIT"
export const UPDATEORGANIZATIONLEVELSETTING_SUCCESS =
  "UPDATEORGANIZATIONLEVELSETTING_SUCCESS"
export const UPDATEORGANIZATIONLEVELSETTING_FAIL =
  "UPDATEORGANIZATIONLEVELSETTING_FAIL"

export const GETSUBSCRIBEORGANIZATIONPACKAGE_INIT =
  "GETSUBSCRIBEORGANIZATION_INIT"
export const GETSUBSCRIBEORGANIZATIONPACKAGE_SUCCESS =
  "GETSUBSCRIBEORGANIZATIONPACKAGE_SUCCESS"
export const GETSUBSCRIBEORGANIZATIONPACKAGE_FAIL =
  "GETSUBSCRIBEORGANIZATIONPACKAGE_FAIL"

export const GETUPGRADABLESUBSCRIPTIONPACAKGE_INIT =
  "GETUPGRADABLESUBSCRIPTIONPACAKGE_INIT"
export const GETUPGRADABLESUBSCRIPTIONPACAKGE_SUCCESS =
  "GETUPGRADABLESUBSCRIPTIONPACAKGE_SUCCESS"
export const GETUPGRADABLESUBSCRIPTIONPACAKGE_FAIL =
  "GETUPGRADABLESUBSCRIPTIONPACAKGE_FAIL"

export const UPGRADESUBSRIPTIONPACKAGE_INIT = "UPGRADESUBSRIPTIONPACKAGE_INIT"
export const UPGRADESUBSRIPTIONPACKAGE_SUCCESS =
  "UPGRADESUBSRIPTIONPACKAGE_SUCCESS"
export const UPGRADESUBSRIPTIONPACKAGE_FAIL = "UPGRADESUBSRIPTIONPACKAGE_FAIL"

export const CANCELSUBCRIPTIONPACKAGE_INIT = "CANCELSUBCRIPTIONPACKAGE_INIT"
export const CANCELSUBCRIPTIONPACKAGE_SUCCESS =
  "CANCELSUBCRIPTIONPACKAGE_SUCCESS"
export const CANCELSUBCRIPTIONPACKAGE_FAIL = "CANCELSUBCRIPTIONPACKAGE_FAIL"

// for get all meeting status
export const ADMIN_MEETINGSTATUS_INIT = "ADMIN_MEETINGSTATUS_INIT"
export const ADMIN_MEETINGSTATUS_SUCCESS = "ADMIN_MEETINGSTATUS_SUCCESS"
export const ADMIN_MEETINGSTATUS_FAIL = "ADMIN_MEETINGSTATUS_FAIL"

// FOR AUTH2 REDUCERS CLEARE MESSAGE
export const CLEARE_MESSAGE = "CLEARE_MESSAGE"

export const UDPATEUSERSETTING_INIT = "UDPATEUSERSETTING_INIT"
export const UDPATEUSERSETTING_SUCCESS = "UDPATEUSERSETTING_SUCCESS"
export const UDPATEUSERSETTING_FAIL = "UDPATEUSERSETTING_FAIL"

export const CHANGEPASSWORD_INIT = "CHANGEPASSWORD_INIT"
export const CHANGEPASSWORD_SUCCESS = "CHANGEPASSWORD_SUCCESS"
export const CHANGEPASSWORD_FAIL = "CHANGEPASSWORD_FAIL"

// FOR GET PACKAGE Reselect
export const RESELECTIONPACKAGE_INIT = "RESELECTIONPACKAGE_INIT"
export const RESELECTIONPACKAGE_SUCCESS = "RESELECTIONPACKAGE_SUCCESS"
export const RESELECTIONPACKAGE_FAIL = "RESELECTIONPACKAGE_FAIL"

// FOR LODER OF ADD USER ACTIONS
export const ADD_USER_LOADER = "ADD_USER_LOADER"
export const ADD_EMAIL_CHECK_FALSE = "ADD_EMAIL_CHECK_FALSE"

// FOR TODO LIST RESPONCE
export const CLEAR_RESPONCE_STATE = "CLEAR_RESPONCE_STATE"

// FOR GET TODO CLEARE MESSAGE LIST RESPONCE
export const GET_CLEAREMESSAGE_GETTODO = "GET_CLEAREMESSAGE_GETTODO"

// FOR UDPATE USERSET TINGCLEARE MESSAGE LIST RESPONCE
export const UDPATEUSERSETTING_MESSAGE_CLEARE =
  "UDPATEUSERSETTING_MESSAGE_CLEARE"

// FOR AUTHENTICATE AFA IS ENABLE OR NOT
export const CHECKINGAUTHENTICATEAFA_INIT = "CHECKINGAUTHENTICATEAFA_INIT"
export const CHECKINGAUTHENTICATEAFA_SUCCESS = "CHECKINGAUTHENTICATEAFA_SUCCESS"
export const CHECKINGAUTHENTICATEAFA_FAIL = "CHECKINGAUTHENTICATEAFA_FAIL"

// FOR SEND TWO FAC OTP CODE
export const SENDTWOFACOTP_INIT = "SENDTWOFACOTP_INIT"
export const SENDTWOFACOTP_SUCCESS = "SENDTWOFACOTP_SUCCESS"
export const SENDTWOFACOTP_FAIL = "SENDTWOFACOTP_FAIL"

// FOR VERIFY TWO FAC OTP CODE
export const VERIFYTWOFACOTP_INIT = "VERIFYTWOFACOTP_INIT"
export const VERIFYTWOFACOTP_SUCCESS = "VERIFYTWOFACOTP_SUCCESS"
export const VERIFYTWOFACOTP_FAIL = "VERIFYTWOFACOTP_FAIL"

// FOR CLEARE MESSAGE OF SET SUB PACK
export const CLEARE_MESSAGE_SUBSPACK = "CLEARE_MESSAGE_SUBSPACK"

// FOR CLEARE RESPONSE MESSAGE OF CHANGE PASSWORD
export const CLEARE_CHANGE_PASSWORD_MESSAGE = "CLEARE_CHANGE_PASSWORD_MESSAGE"

//PASSWORD UPDATION ON FORGOT PASSWORD

export const PASSWORD_UPDATE_INIT = "PASSWORD_UPDATE_INIT"
export const PASSWORD_UPDATE_SUCCESS = "PASSWORD_UPDATE_SUCCESS"
export const PASSWORD_UPDATE_FAIL = "PASSWORD_UPDATE_FAIL"

//Revoke

export const REVOKE_INIT = "REVOKE_INIT"
export const REVOKE_SUCCESS = "REVOKE_SUCCESS"
export const REVOKE_FAIL = "REVOKE_FAIL"

export const GET_USERS_DETAILS_INIT = "GET_USERS_DETAILS_INIT"
export const GET_USERS_DETAILS_SUCCESS = "GET_USERS_DETAILS_SUCCESS"
export const GET_USERS_DETAILS_FAIL = "GET_USERS_DETAILS_FAIL"

export const UPDATE_USER_PROFILE_INIT = "UPDATE_USER_PROFILE_INIT"
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS"
export const UPDATE_USER_PROFILE_FAIL = "UPDATE_USER_PROFILE_FAIL"

export const AUTH2_REDUCER_LOADER = "AUTH2_REDUCER_LOADER"

export const VIDEO_BOX_OPEN = "VIDEO_BOX_OPEN"
export const VIDEO_BOX_CLOSE = "VIDEO_BOX_CLOSE"
export const VIDEO_BOX_MINIMIZE = "VIDEO_BOX_MINIMIZE"
export const VIDEO_BOX_NORMAL = "VIDEO_BOX_NORMAL"
export const VIDEO_BOX_MAXIMIZE = "VIDEO_BOX_MAXIMIZE"
export const OPENING_GROUP_CALL = "OPENING_GROUP_CALL"

export const INCOMING_CALL_OPEN = "INCOMING_CALL_OPEN"

export const ADD_NOTES_INIT = "ADD_NOTES_INIT"
export const ADD_NOTES_SUCCESS = "ADD_NOTES_SUCCESS"
export const ADD_NOTES_FAIL = "ADD_NOTES_FAIL"

export const UPDATE_NOTES_INIT = "UPDATE_NOTES_INIT"
export const UPDATE_NOTES_SUCCESS = "UPDATE_NOTES_SUCCESS"
export const UPDATE_NOTES_FAIL = "UPDATE_NOTES_FAIL"

export const GET_NOTES_INIT = "GET_NOTES_INIT"
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS"
export const GET_NOTES_FAIL = "GET_NOTES_FAIL"

export const GET_NOTES_BY_NOTESID_INIT = "GET_NOTES_BY_NOTESID_INIT"
export const GET_NOTES_BY_NOTESID_SUCCESS = "GET_NOTES_BY_NOTESID_SUCCESS"
export const GET_NOTES_BY_NOTESID_FAIL = "GET_NOTES_BY_NOTESID_FAIL"

export const GET_NOTES_ATTACHMENTS_INIT = "GET_NOTES_ATTACHMENTS_INIT"
export const GET_NOTES_ATTACHMENTS_SUCCESS = "GET_NOTES_ATTACHMENTS_SUCCESS"
export const GET_NOTES_ATTACHMENTS_FAIL = "GET_NOTES_ATTACHMENTS_FAIL"

export const ALL_MEETINGS_MQTT = "ALL_MEETINGS_MQTT"

export const DELETE_ORGANIZATION_INIT = "DELETE_ORGANIZATION_INIT"
export const DELETE_ORGANIZATION_SUCCESS = "DELETE_ORGANIZATION_SUCCESS"
export const DELETE_ORGANIZATION_FAIL = "DELETE_ORGANIZATION_FAIL"

export const CLEAR_NOTES_RESPONSEMESSAGE = "CLEAR_NOTES_RESPONSEMESSAGE"

export const REFRESH_TOKEN_TALK_SUCCESS = "REFRESH_TOKEN_TALK_SUCCESS"
export const REFRESH_TOKEN_TALK_FAIL = "REFRESH_TOKEN_TALK_FAIL"

export const GET_USERCHATS_INIT = "GET_USERCHATS_INIT"
export const GET_USERCHATS_SUCCESS = "GET_USERCHATS_SUCCESS"
export const GET_USERCHATS_FAIL = "GET_USERCHATS_FAIL"

export const GET_OTOUSERMESSAGES_INIT = "GET_OTOUSERMESSAGES_INIT"
export const GET_OTOUSERMESSAGES_SUCCESS = "GET_OTOUSERMESSAGES_SUCCESS"
export const GET_OTOUSERMESSAGES_FAIL = "GET_OTOUSERMESSAGES_FAIL"

export const GET_OTOUSERUNDELIVEREDMESSAGES_INIT =
  "GET_OTOUSERUNDELIVEREDMESSAGES_INIT"
export const GET_OTOUSERUNDELIVEREDMESSAGES_SUCCESS =
  "GET_OTOUSERUNDELIVEREDMESSAGES_SUCCESS"
export const GET_OTOUSERUNDELIVEREDMESSAGES_FAIL =
  "GET_OTOUSERUNDELIVEREDMESSAGES_FAIL"

export const GET_GROUPMESSAGES_INIT = "GET_GROUPMESSAGES_INIT"
export const GET_GROUPMESSAGES_SUCCESS = "GET_GROUPMESSAGES_SUCCESS"
export const GET_GROUPMESSAGES_FAIL = "GET_GROUPMESSAGES_FAIL"

export const GET_BROADCASTMESSAGES_INIT = "GET_BROADCASTMESSAGES_INIT"
export const GET_BROADCASTMESSAGES_SUCCESS = "GET_BROADCASTMESSAGES_SUCCESS"
export const GET_BROADCASTMESSAGES_FAIL = "GET_BROADCASTMESSAGES_FAIL"

export const GET_ARCHIVEDDATABYUSERID_INIT = "GET_ARCHIVEDDATABYUSERID_INIT"
export const GET_ARCHIVEDDATABYUSERID_SUCCESS =
  "GET_ARCHIVEDDATABYUSERID_SUCCESS"
export const GET_ARCHIVEDDATABYUSERID_FAIL = "GET_ARCHIVEDDATABYUSERID_FAIL"

export const GET_FLAGMESSAGES_INIT = "GET_FLAGMESSAGES_INIT"
export const GET_FLAGMESSAGES_SUCCESS = "GET_FLAGMESSAGES_SUCCESS"
export const GET_FLAGMESSAGES_FAIL = "GET_FLAGMESSAGES_FAIL"

export const GET_FOLLOWMESSAGES_INIT = "GET_FOLLOWMESSAGES_INIT"
export const GET_FOLLOWMESSAGES_SUCCESS = "GET_FOLLOWMESSAGES_SUCCESS"
export const GET_FOLLOWMESSAGES_FAIL = "GET_FOLLOWMESSAGES_FAIL"

export const GET_RECENTTAGS_INIT = "GET_RECENTTAGS_INIT"
export const GET_RECENTTAGS_SUCCESS = "GET_RECENTTAGS_SUCCESS"
export const GET_RECENTTAGS_FAIL = "GET_RECENTTAGS_FAIL"

export const GET_TAGSMESSAGES_INIT = "GET_TAGSMESSAGES_INIT"
export const GET_TAGSMESSAGES_SUCCESS = "GET_TAGSMESSAGES_SUCCESS"
export const GET_TAGSMESSAGES_FAIL = "GET_TAGSMESSAGES_FAIL"

export const GET_MESSAGESENTRECEIVETIME_INIT = "GET_MESSAGESENTRECEIVETIME_INIT"
export const GET_MESSAGESENTRECEIVETIME_SUCCESS =
  "GET_MESSAGESENTRECEIVETIME_SUCCESS"
export const GET_MESSAGESENTRECEIVETIME_FAIL = "GET_MESSAGESENTRECEIVETIME_FAIL"

export const GET_RECENTFLAGCOUNT_INIT = "GET_RECENTFLAGCOUNT_INIT"
export const GET_RECENTFLAGCOUNT_SUCCESS = "GET_RECENTFLAGCOUNT_SUCCESS"
export const GET_RECENTFLAGCOUNT_FAIL = "GET_RECENTFLAGCOUNT_FAIL"

export const GET_RECENTFOLLOWDATACOUNT_INIT = "GET_RECENTFOLLOWDATACOUNT_INIT"
export const GET_RECENTFOLLOWDATACOUNT_SUCCESS =
  "GET_RECENTFOLLOWDATACOUNT_SUCCESS"
export const GET_RECENTFOLLOWDATACOUNT_FAIL = "GET_RECENTFOLLOWDATACOUNT_FAIL"

export const GET_ALLRECENTTAGSCOUNT_INIT = "GET_ALLRECENTTAGSCOUNT_INIT"
export const GET_ALLRECENTTAGSCOUNT_SUCCESS = "GET_ALLRECENTTAGSCOUNT_SUCCESS"
export const GET_ALLRECENTTAGSCOUNT_FAIL = "GET_ALLRECENTTAGSCOUNT_FAIL"

export const GET_RECENTDATAARCHIVECOUNT_INIT = "GET_RECENTDATAARCHIVECOUNT_INIT"
export const GET_RECENTDATAARCHIVECOUNT_SUCCESS =
  "GET_RECENTDATAARCHIVECOUNT_SUCCESS"
export const GET_RECENTDATAARCHIVECOUNT_FAIL = "GET_RECENTDATAARCHIVECOUNT_FAIL"

export const GET_BLOCKEDUSERSCOUNT_INIT = "GET_BLOCKEDUSERSCOUNT_INIT"
export const GET_BLOCKEDUSERSCOUNT_SUCCESS = "GET_BLOCKEDUSERSCOUNT_SUCCESS"
export const GET_BLOCKEDUSERSCOUNT_FAIL = "GET_BLOCKEDUSERSCOUNT_FAIL"

export const GET_BLOCKEDUSERS_INIT = "GET_BLOCKEDUSERS_INIT"
export const GET_BLOCKEDUSERS_SUCCESS = "GET_BLOCKEDUSERS_SUCCESS"
export const GET_BLOCKEDUSERS_FAIL = "GET_BLOCKEDUSERS_FAIL"

export const GET_ALLUSERS_INIT = "GET_ALLUSERS_INIT"
export const GET_ALLUSERS_SUCCESS = "GET_ALLUSERS_SUCCESS"
export const GET_ALLUSERS_FAIL = "GET_ALLUSERS_FAIL"

export const GET_ALLUSERSGROUPSROOMSLIST_INIT =
  "GET_ALLUSERSGROUPSROOMSLIST_INIT"
export const GET_ALLUSERSGROUPSROOMSLIST_SUCCESS =
  "GET_ALLUSERSGROUPSROOMSLIST_SUCCESS"
export const GET_ALLUSERSGROUPSROOMSLIST_FAIL =
  "GET_ALLUSERSGROUPSROOMSLIST_FAIL"

export const GET_ACTIVEUSERSBYGROUPID_INIT = "GET_ACTIVEUSERSBYGROUPID_INIT"
export const GET_ACTIVEUSERSBYGROUPID_SUCCESS =
  "GET_ACTIVEUSERSBYGROUPID_SUCCESS"
export const GET_ACTIVEUSERSBYGROUPID_FAIL = "GET_ACTIVEUSERSBYGROUPID_FAIL"

export const GET_ACTIVEUSERSBYROOMID_INIT = "GET_ACTIVEUSERSBYROOMID_INIT"
export const GET_ACTIVEUSERSBYROOMID_SUCCESS = "GET_ACTIVEUSERSBYROOMID_SUCCESS"
export const GET_ACTIVEUSERSBYROOMID_FAIL = "GET_ACTIVEUSERSBYROOMID_FAIL"

export const GET_ACTIVEUSERSBYBROADCASTID_INIT =
  "GET_ACTIVEUSERSBYBROADCASTID_INIT"
export const GET_ACTIVEUSERSBYBROADCASTID_SUCCESS =
  "GET_ACTIVEUSERSBYBROADCASTID_SUCCESS"
export const GET_ACTIVEUSERSBYBROADCASTID_FAIL =
  "GET_ACTIVEUSERSBYBROADCASTID_FAIL"

export const GET_COMMITTEE_BYUSERID_INIT = "GET_COMMITTEE_BYUSERID_INIT"
export const GET_COMMITTEE_BYUSERID_SUCCESS = "GET_COMMITTEE_BYUSERID_INIT"
export const GET_COMMITTEE_BYUSERID_FAIL = "GET_COMMITTEE_BYUSERID_INIT"

export const ADD_COMMITTEE_INIT = "ADD_COMMITTEE_INIT"
export const ADD_COMMITTEE_SUCCESS = "ADD_COMMITTEE_SUCCESS"
export const ADD_COMMITTEE_FAIL = "ADD_COMMITTEE_FAIL"

export const CLEAR_MESSAGE_RESPONSE_COMMITTEE =
  "CLEAR_MESSAGE_RESPONSE_COMMITTEE"

export const GET_COMMITTEE_BYCOMMITTEEID_INIT =
  "GET_COMMITTEE_BYCOMMITTEEID_INIT"
export const GET_COMMITTEE_BYCOMMITTEEID_SUCCESS =
  "GET_COMMITTEE_BYCOMMITTEEID_SUCCESS"
export const GET_COMMITTEE_BYCOMMITTEEID_FAIL =
  "GET_COMMITTEE_BYCOMMITTEEID_FAIL"

export const GET_GROUPS_BYUSERID_INIT = "GET_GROUPS_BYUSERID_INIT"
export const GET_GROUPS_BYUSERID_SUCCESS = "GET_GROUPS_BYUSERID_SUCCESS"
export const GET_GROUPS_BYUSERID_FAIL = "GET_GROUPS_BYUSERID_FAIL"

export const GET_GROUPS_BYGROUPID_INIT = "GET_GROUPS_BYGROUPID_INIT"
export const GET_GROUPS_BYGROUPID_SUCCESS = "GET_GROUPS_BYGROUPID_SUCCESS"
export const GET_GROUPS_BYGROUPID_FAIL = "GET_GROUPS_BYGROUPID_FAIL"

export const UPDATE_GROUP_INIT = "UPDATE_GROUP_INIT"
export const UPDATE_GROUP_SUCCESSS = "UPDATE_GROUP_SUCCESSS"
export const UPDATE_GROUP_FAIL = "UPDATE_GROUP_FAIL"

export const CLEAR_RESPONSE_MESSAGE_GROUPS = "CLEAR_RESPONSE_MESSAGE_GROUPS"

export const CREATE_GROUP_INIT = "CREATE_GROUP_INIT"
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS"
export const CREATE_GROUP_FAIL = "CREATE_GROUP_FAIL"

export const GET_GROUP_MEMBERS_ROLES_INIT = "GET_GROUP_MEMBERS_ROLES_INIT"
export const GET_GROUP_MEMBERS_ROLES_SUCCESS = "GET_GROUP_MEMBERS_ROLES_SUCCESS"
export const GET_GROUP_MEMBERS_ROLES_FAIL = "GET_GROUP_MEMBERS_ROLES_FAIL"

export const GET_GROUP_ORGANIZATION_TYPE_INIT =
  "GET_GROUP_ORGANIZATION_TYPE_INIT"
export const GET_GROUP_ORGANIZATION_TYPE_SUCCESS =
  "GET_GROUP_ORGANIZATION_TYPE_SUCCESS"
export const GET_GROUP_ORGANIZATION_TYPE_FAIL =
  "GET_GROUP_ORGANIZATION_TYPE_FAIL"

export const UPDATE_GROUP_STATUS_INIT = "UPDATE_GROUP_STATUS_INIT"
export const UPDATE_GROUP_STATUS_SUCCESS = "UPDATE_GROUP_STATUS_SUCCESS"
export const UPDATE_GROUP_STATUS_FAIL = "UPDATE_GROUP_STATUS_FAIL"

export const GET_ALL_COMMITTEES_BY_USERID_INIT =
  "GET_ALL_COMMITTEES_BY_USERID_INIT"
export const GET_ALL_COMMITTEES_BY_USERID_SUCCESS =
  "GET_ALL_COMMITTEES_BY_USER_ID_SUCCESS"
export const GET_ALL_COMMITTEES_BY_USERID_FAIL =
  "GET_ALL_COMMITTEES_BY_USER_ID_FAIL"

export const CREATE_COMMITTEE_INIT = "CREATE_COMMITTEE_INIT"
export const CREATE_COMMITTEE_SUCCESS = "CREATE_COMMITTEE_SUCCESS"
export const CREATE_COMMITTEE_FAIL = "CREATE_COMMITTEE_FAIL"

export const GET_ALL_COMMITTEE_TYPES_INIT = "GET_ALL_COMMITTEE_TYPES_INIT"
export const GET_ALL_COMMITTEE_TYPES_SUCCESS = "GET_ALL_COMMITTEE_TYPES_SUCCESS"
export const GET_ALL_COMMITTEE_TYPES_FAIL = "GET_ALL_COMMITTEE_TYPES_FAIL"

export const GET_COMMITTEE_MEMBERS_ROLES_INIT =
  "GET_COMMITTEE_MEMBERS_ROLES_INIT"
export const GET_COMMITTEE_MEMBERS_ROLES_SUCCESS =
  "GET_COMMITTEE_MEMBERS_ROLES_SUCCESS"
export const GET_COMMITTEE_MEMBERS_ROLES_FAIL =
  "GET_COMMITTEE_MEMBERS_ROLES_FAIL"

export const OTO_MESSAGESEND_INIT = "OTO_MESSAGESEND_INIT"
export const OTO_MESSAGESEND_SUCCESS = "OTO_MESSAGESEND_SUCCESS"
export const OTO_MESSAGESEND_FAIL = "OTO_MESSAGESEND_FAIL"

export const UPDATE_COMMITTEE_STATUS_INIT = "UPDATE_COMMITTEE_STATUS_INIT"
export const UPDATE_COMMITTEE_STATUS_SUCCESS = "UPDATE_COMMITTEE_STATUS_SUCCESS"
export const UPDATE_COMMITTEE_STATUS_FAIL = "UPDATE_COMMITTEE_STATUS_FAIL"

export const UPDATE_COMMITTEE_INIT = "UPDATE_COMMITTEE_INIT"
export const UPDATE_COMMITTEE_SUCCESS = "UPDATE_COMMITTEE_SUCCESS"
export const UPDATE_COMMITTEE_FAIL = "UPDATE_COMMITTEE_FAIL"

export const PRIVATEGROUP_MESSAGESEND_INIT = "PRIVATEGROUP_MESSAGESEND_INIT"
export const PRIVATEGROUP_MESSAGESEND_NOTIFICATION =
  "PRIVATEGROUP_MESSAGESEND_NOTIFICATION"

export const BLOCK_UNBLOCK_USER_INIT = "BLOCK_UNBLOCK_USER_INIT"
export const BLOCK_UNBLOCK_USER_NOTIFICATION = "BLOCK_UNBLOCK_USER_NOTIFICATION"

export const REALTIME_GROUPS_RESPONSE = "REALTIME_GROUPS_RESPONSE"
export const REALTIME_GROUPS_STATUS_RESPONSE = "REALTIME_GROUPS_STATUS_RESPONSE"
// export const REALTIME_GROUPS_RESPONSE = "REALTIME_GROUPS_RESPONSE"

export const DELETE_SINGLEMESSAGE_INIT = "DELETE_SINGLEMESSAGE_INIT"
export const DELETE_SINGLEMESSAGE_SUCCESS = "DELETE_SINGLEMESSAGE_SUCCESS"
export const DELETE_SINGLEMESSAGE_FAIL = "DELETE_SINGLEMESSAGE_FAIL"

export const BROADCAST_MESSAGESEND_INIT = "BROADCAST_MESSAGESEND_INIT"
export const BROADCAST_MESSAGESEND_NOTIFICATION =
  "BROADCAST_MESSAGESEND_NOTIFICATION"

export const REALTIME_COMMITTEES_RESPONSE = "REALTIME_COMMITTEES_RESPONSE"
export const REALTIME_COMMITTEES_STATUS_RESPONSE =
  "REALTIME_COMMITTEES_STATUS_RESPONSE"

export const GET_ALL_VOTING_METHOD_INIT = "GET_ALL_VOTING_METHOD_INIT"
export const GET_ALL_VOTING_METHOD_SUCCESS = "GET_ALL_VOTING_METHOD_SUCCESS"
export const GET_ALL_VOTING_METHOD_FAIL = "GET_ALL_VOTING_METHOD_FAIL"

export const GET_ALL_RESOLUTION_STATUS_INIT = "GET_ALL_RESOLUTION_STATUS_INIT"
export const GET_ALL_RESOLUTION_STATUS_SUCCESS =
  "GET_ALL_RESOLUTION_STATUS_SUCCESS"
export const GET_ALL_RESOLUTION_STATUS_FAIL = "GET_ALL_RESOLUTION_STATUS_FAIL"

export const GET_RESOLUTIONS_INIT = "GET_RESOLUTIONS_INIT"
export const GET_RESOLUTIONS_SUCCESS = "GET_RESOLUTIONS_SUCCESS"
export const GET_RESOLUTIONS_FAIL = "GET_RESOLUTIONS_FAIL"
export const SET_MQTT_CLIENT = "SET_MQTT_CLIENT"

export const MQTT_INSERT_OTO_MESSAGE = "MQTT_INSERT_OTO_MESSAGE"
export const MQTT_INSERT_PRIVATEGROUP_MESSAGE =
  "MQTT_INSERT_PRIVATEGROUP_MESSAGE"

export const SCHEDULE_RESOLUTION_INIT = "SCHEDULE_RESOLUTION_INIT"
export const SCHEDULE_RESOLUTION_SUCCESS = "SCHEDULE_RESOLUTION_SUCCESS"
export const SCHEDULE_RESOLUTION_FAIL = "SCHEDULE_RESOLUTION_FAIL"

export const ADD_UPDATE_DETAILS_RESOLUTION_INIT =
  "ADD_UPDATE_DETAILS_RESOLUTION_INIT"
export const ADD_UPDATE_DETAILS_RESOLUTION_SUCCESS =
  "ADD_UPDATE_DETAILS_RESOLUTION_SUCCESS"
export const ADD_UPDATE_DETAILS_RESOLUTION_FAIL =
  "ADD_UPDATE_DETAILS_RESOLUTION_FAIL"

export const DELETE_NOTE_INIT = "DELETE_NOTE_INIT"
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS"
export const DELETE_NOTE_FAIL = "DELETE_NOTE_FAIL"

export const GET_ALL_ORGANIZATION_GROUPS_INIT =
  "GET_ALL_ORGANIZATION_GROUPS_INIT"
export const GET_ALL_ORGANIZATION_GROUPS_SUCCESS =
  "GET_ALL_ORGANIZATION_GROUPS_SUCCESS"
export const GET_ALL_ORGANIZATION_GROUPS_FAIL =
  "GET_ALL_ORGANIZATION_GROUPS_FAIL"

export const COMMITTEE_GROUP_MAPPING_INIT = "COMMITTEE_GROUP_MAPPING_INIT"
export const COMMITTEE_GROUP_MAPPING_SUCCESS = "COMMITTEE_GROUP_MAPPING_SUCCESS"
export const COMMITTEE_GROUP_MAPPING_FAIL = "COMMITTEE_GROUP_MAPPING_FAIL"

export const DELETE_TODO_INIT = "DELETE_TODO_INIT"
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS"
export const DELETE_TODO_FAIL = "DELETE_TODO_FAIL"

export const GET_RESOLUTION_BY_RESOLUTION_ID_INIT =
  "GET_RESOLUTION_BY_RESOLUTION_ID_INIT"
export const GET_RESOLUTION_BY_RESOLUTION_ID_SUCCESS =
  "GET_RESOLUTION_BY_RESOLUTION_ID_SUCCESS"
export const GET_RESOLUTION_BY_RESOLUTION_ID_FAIL =
  "GET_RESOLUTION_BY_RESOLUTION_ID_FAIL"

export const GET_RESOLUTION_RESULTS_DETAILS_INIT =
  "GET_RESOLUTION_RESULTS_DETAILS_INIT"
export const GET_RESOLUTION_RESULTS_DETAILS_SUCCESS =
  "GET_RESOLUTION_RESULTS_DETAILS_SUCCESS"
export const GET_RESOLUTION_RESULTS_DETAILS_FAIL =
  "GET_RESOLUTION_RESULTS_DETAILS_FAIL"

export const GET_VOTESDETAILSBYID_INIT = "GET_VOTESDETAILSBYID_INIT"
export const GET_VOTESDETAILSBYID_SUCCESS = "GET_VOTESDETAILSBYID_SUCCESS"
export const GET_VOTESDETAILSBYID_FAIL = "GET_VOTESDETAILSBYID_FAIL"

export const CANCEL_RESOLUTION_INIT = "CANCEL_RESOLUTION_INIT"
export const CANCEL_RESOLUTION_SUCCESS = "CANCEL_RESOLUTION_SUCCESS"
export const CANCEL_RESOLUTION_FAIL = "CANCEL_RESOLUTION_FAIL"

export const CLOSE_RESOLUTION_INIT = "CLOSE_RESOLUTION_INIT"
export const CLOSE_RESOLUTION_SUCCESS = "CLOSE_RESOLUTION_SUCCESS"
export const CLOSE_RESOLUTION_FAIL = "CLOSE_RESOLUTION_FAIL"

export const UPDATE_VOTE_INIT = "UPDATE_VOTE_INIT"
export const UPDATE_VOTE_SUCCESS = "UPDATE_VOTE_SUCCESS"
export const UPDATE_VOTE_FAIL = "UPDATE_VOTE_FAIL"

export const UPDATE_RESOLUTION_BY_RESOLUTION_ID_INIT =
  "UPDATE_RESOLUTION_BY_RESOLUTION_ID_INIT"
export const UPDATE_RESOLUTION_BY_RESOLUTION_ID_SUCCESS =
  "UPDATE_RESOLUTION_BY_RESOLUTION_ID_SUCCESS"
export const UPDATE_RESOLUTION_BY_RESOLUTION_ID_FAIL =
  "UPDATE_RESOLUTION_BY_RESOLUTION_ID_FAIL"

export const CREATE_PRIVATEGROUP_INIT = "CREATE_PRIVATEGROUP_INIT"
export const CREATE_PRIVATEGROUP_NOTIFICATION =
  "CREATE_PRIVATEGROUP_NOTIFICATION"

export const GET_PRIVATEGROUPMEMBERS_INIT = "GET_PRIVATEGROUPMEMBERS_INIT"
export const GET_PRIVATEGROUPMEMBERS_SUCCESS = "GET_PRIVATEGROUPMEMBERS_SUCCESS"
export const GET_PRIVATEGROUPMEMBERS_FAIL = "GET_PRIVATEGROUPMEMBERS_FAIL"

export const STAR_UNSTAR_MESSAGE_INIT = "STAR_UNSTAR_MESSAGE_INIT"
export const STAR_UNSTAR_MESSAGE_NOTIFICATION =
  "STAR_UNSTAR_MESSAGE_NOTIFICATION"

export const RECENT_ACTIVITYDATA_MQTT = "RECENT_ACTIVITYDATA_MQTT"

export const RECENT_TODOCOUNTER = "RECENT_TODOCOUNTER"
export const RECENT_MEETINGCOUNTER = "RECENT_MEETINGCOUNTER"
export const UPCOMINGEVENTS_MQTT = "UPCOMINGEVENTS_MQTT"

export const GET_BLLINGINFORMATION_INIT = "GET_BLLINGINFORMATION_INIT"
export const GET_BLLINGINFORMATION_SUCCESS = "GET_BLLINGINFORMATION_SUCCESS"
export const GET_BLLINGINFORMATION_FAIL = "GET_BLLINGINFORMATION_FAIL"

export const PAYOUTSTANDING_INIT = "PAYOUTSTANDING_INIT"
export const PAYOUTSTANDING_SUCCESS = "PAYOUTSTANDING_SUCCESS"
export const PAYOUTSTANDING_FAIL = "PAYOUTSTANDING_FAIL"

export const INVOICEANDPAYMENTHISTORY_INIT = "INVOICEANDPAYMENTHISTORY_INIT"
export const INVOICEANDPAYMENTHISTORY_SUCCESS =
  "INVOICEANDPAYMENTHISTORY_SUCCESS"
export const INVOICEANDPAYMENTHISTORY_FAIL = "INVOICEANDPAYMENTHISTORY_FAIL"

export const GET_ACTIVECHATID = "GET_ACTIVECHATID"
export const GET_ACTIVEMESSAGEID = "GET_ACTIVEMESSAGEID"

export const CLEAR_RESPONSEMESSAGE_RESOLUTION =
  "CLEAR_RESPONSEMESSAGE_RESOLUTION"

export const SAVEFILES_DATAROOM_INIT = "SAVEFILES_DATAROOM_INIT"
export const SAVEFILES_DATAROOM_SUCCESS = "SAVEFILES_DATAROOM_SUCCESS"
export const SAVEFILES_DATAROOM_FAIL = "SAVEFILES_DATAROOM_FAIL"

export const UPLOAD_DOCUMENTS_DATAROOM_INIT = "UPLOAD_DOCUMENTS_DATAROOM_INIT"
export const UPLOAD_DOCUMENTS_DATAROOM_SUCCESS =
  "UPLOAD_DOCUMENTS_DATAROOM_SUCCESS"
export const UPLOAD_DOCUMENTS_DATAROOM_FAIL = "UPLOAD_DOCUMENTS_DATAROOM_FAIL"

export const SAVE_FOLDER_DATAROOM_INIT = "SAVE_FOLDER_DATAROOM_INIT"
export const SAVE_FOLDER_DATAROOM_SUCCESS = "SAVE_FOLDER_DATAROOM_SUCCESS"
export const SAVE_FOLDER_DATAROOM_FAIL = "SAVE_FOLDER_DATAROOM_FAIL"

export const GETMYDOCUMENTS_DATAROOM_INIT = "GETMYDOCUMENTS_DATAROOM_INIT"
export const GETMYDOCUMENTS_DATAROOM_SUCCESS = "GETMYDOCUMENTS_DATAROOM_SUCCESS"
export const GETMYDOCUMENTS_DATAROOM_FAIL = "GETMYDOCUMENTS_DATAROOM_FAIL"

export const GET_FOLDER_DOCUMENTS_DATAROOM_INIT =
  "GET_FOLDER_DOCUMENTS_DATAROOM_INIT"
export const GET_FOLDER_DOCUMENTS_DATAROOM_SUCCESS =
  "GET_FOLDER_DOCUMENTS_DATAROOM_SUCCESS"
export const GET_FOLDER_DOCUMENTS_DATAROOM_FAIL =
  "GET_FOLDER_DOCUMENTS_DATAROOM_FAIL"

export const CREATE_FOLDER_DATAROOM_INIT = "CREATE_FOLDER_DATAROOM_INIT"
export const CREATE_FOLDER_DATAROOM_SUCCESS = "CREATE_FOLDER_DATAROOM_SUCCESS"
export const CREATE_FOLDER_DATAROOM_FAIL = "CREATE_FOLDER_DATAROOM_FAIL"

export const GETALLDOCUMENTSANDFOLDER_DATAROOM_INIT =
  "GETALLDOCUMENTSANDFOLDER_DATAROOM_INIT"
export const GETALLDOCUMENTSANDFOLDER_DATAROOM_SUCCESS =
  "GETALLDOCUMENTSANDFOLDER_DATAROOM_SUCCESS"
export const GETALLDOCUMENTSANDFOLDER_DATAROOM_FAIL =
  "GETALLDOCUMENTSANDFOLDER_DATAROOM_FAIL"

export const SHAREFILES_DATAROOM_INIT = "SHAREFILES_DATAROOM_INIT"
export const SHAREFILES_DATAROOM_SUCCESS = "SHAREFILES_DATAROOM_SUCCESS"
export const SHAREFILES_DATAROOM_FAIL = "SHAREFILES_DATAROOM_FAIL"

export const SEARCH_VOTERRESOLUTION_INIT = "SEARCH_VOTERRESOLUTION_INIT"
export const SEARCH_VOTERRESOLUTION_SUCCESS = "SEARCH_VOTERRESOLUTION_SUCCESS"
export const SEARCH_VOTERRESOLUTION_FAIL = "SEARCH_VOTERRESOLUTION_FAIL"

export const SHAREFOLDERS_DATAROOM_INIT = "SHAREFOLDERS_DATAROOM_INIT"
export const SHAREFOLDERS_DATAROOM_SUCCESS = "SHAREFOLDERS_DATAROOM_SUCCESS"
export const SHAREFOLDERS_DATAROOM_FAIL = "SHAREFOLDERS_DATAROOM_FAIL"

export const GET_ALLSHAREDFILESANDFOLDER_DATAROOM_INIT =
  "GET_ALLSHAREDFILESANDFOLDER_DATAROOM_INIT"
export const GET_ALLSHAREDFILESANDFOLDER_DATAROOM_SUCCESS =
  "GET_ALLSHAREDFILESANDFOLDER_DATAROOM_SUCCESS"
export const GET_ALLSHAREDFILESANDFOLDER_DATAROOM_FAIL =
  "GET_ALLSHAREDFILESANDFOLDER_DATAROOM_FAIL"

export const CURRENTRESOLUTIONSTATE = "CURRENTRESOLUTIONSTATE"
export const RESOLUTIONCLOSEDORNOTCLOSED = "RESOLUTIONCLOSEDORNOTCLOSED"

export const MQTT_BLOCK_USER = "MQTT_BLOCK_USER"
export const MQTT_UNBLOCK_USER = "MQTT_UNBLOCK_USER"

export const MQTT_STAR_MESSAGE = "MQTT_STAR_MESSAGE"
export const MQTT_UNSTAR_MESSAGE = "MQTT_UNSTAR_MESSAGE"

export const MQTT_GROUP_CREATED = "MQTT_GROUP_CREATED"

export const MQTT_UNREAD_MESSAGE_COUNT = "MQTT_UNREAD_MESSAGE_COUNT"

export const DELETEFILE_DATAROOM_INIT = "DELETEFILE_DATAROOM_INIT"
export const DELETEFILE_DATAROOM_SUCCESS = "DELETEFILE_DATAROOM_SUCCESS"
export const DELETEFILE_DATAROOM_FAIL = "DELETEFILE_DATAROOM_FAIL"

export const FOLDERISEXIST_INIT = "FOLDERISEXIST_INIT"
export const FOLDERISEXIST_SUCCESS = "FOLDERISEXIST_SUCCESS"
export const FOLDERISEXIST_FAIL = "FOLDERISEXIST_FAIL"

export const FILEISEXIST_INIT = "FILEISEXIST_INIT"
export const FILEISEXIST_SUCCESS = "FILEISEXIST_SUCCESS"
export const FILEISEXIST_FAIL = "FILEISEXIST_FAIL"

export const DELETEFOLDER_DATAROOM_INIT = "DELETEFOLDER_DATAROOM_INIT"
export const DELETEFOLDER_DATAROOM_SUCCESS = "DELETEFOLDER_DATAROOM_SUCCESS"
export const DELETEFOLDER_DATAROOM_FAIL = "DELETEFOLDER_DATAROOM_FAIL"

export const UPLOAD_ATTACHMENTS = "UPLOAD_ATTACHMENTS"

export const UPDATE_PRIVATEGROUP_INIT = "UPDATE_PRIVATEGROUP_INIT"
export const UPDATE_PRIVATEGROUP_NOTIFICATION =
  "UPDATE_PRIVATEGROUP_NOTIFICATION"

export const MQTT_GROUP_UPDATED = "MQTT_GROUP_UPDATED"
export const LEAVE_GROUP_INIT = "LEAVE_GROUP_INIT"
export const LEAVE_GROUP_NOTIFICATION = "LEAVE_GROUP_NOTIFICATION"

export const RESET_LEAVE_GROUP_MESSAGE = "RESET_LEAVE_GROUP_MESSAGE"
export const RESET_GROUP_MODIFY_MESSAGE = "RESET_GROUP_MODIFY_MESSAGE"

export const CREATE_SHOUTALL_INIT = "CREATE_SHOUTALL_INIT"
export const CREATE_SHOUTALL_SUCCESS = "CREATE_SHOUTALL_SUCCESS"
export const CREATE_SHOUTALL_FAIL = "CREATE_SHOUTALL_FAIL"

export const DELETE_SHOUT_INIT = "DELETE_SHOUT_INIT"
export const DELETE_SHOUT_SUCCESS = "DELETE_SHOUT_SUCCESS"
export const DELETE_SHOUT_FAIL = "DELETE_SHOUT_FAIL"

export const RESET_SHOUTALL_CREATED_MESSAGE = "RESET_SHOUTALL_CREATED_MESSAGE"

export const MQTT_INSERT_BROADCAST_MESSAGE = "MQTT_INSERT_BROADCAST_MESSAGE"

export const UPDATE_SHOUTALL_INIT = "UPDATE_SHOUTALL_INIT"
export const UPDATE_SHOUTALL_SUCCESS = "UPDATE_SHOUTALL_SUCCESS"
export const UPDATE_SHOUTALL_FAIL = "UPDATE_SHOUTALL_FAIL"

export const INSERT_BULKMESSAGES_INIT = "INSERT_BULKMESSAGES_INIT"
export const INSERT_BULKMESSAGES_SUCCESS = "INSERT_BULKMESSAGES_SUCCESS"
export const INSERT_BULKMESSAGES_FAIL = "INSERT_BULKMESSAGES_FAIL"

export const OTO_RETRY_FLAG = "OTO_RETRY_FLAG"

export const DOWNLOAD_CHAT_INIT = "DOWNLOAD_CHAT_INIT"
export const DOWNLOAD_CHAT_SUCCESS = "DOWNLOAD_CHAT_SUCCESS"
export const DOWNLOAD_CHAT_FAIL = "DOWNLOAD_CHAT_FAIL"

export const GOOGLEVALIDTOKEN_INIT = "GOOGLEVALIDTOKEN_INIT"
export const GOOGLEVALIDTOKEN_SUCCESS = "GOOGLEVALIDTOKEN_SUCCESS"
export const GOOGLEVALIDTOKEN_FAIL = "GOOGLEVALIDTOKEN_FAIL"

export const REVOKETOKEN_INIT = "REVOKETOKEN_INIT"
export const REVOKETOKEN_SUCCESS = "REVOKETOKEN_SUCCESS"
export const REVOKETOKEN_FAIL = "REVOKETOKEN_FAIL"

export const SEARCH_USER_MEETINGS_INIT = "SEARCH_USER_MEETINGS_INIT"
export const SEARCH_USER_MEETINGS_SUCCESS = "SEARCH_USER_MEETINGS_SUCCESS"
export const SEARCH_USER_MEETINGS_FAIL = "SEARCH_USER_MEETINGS_FAIL"

export const ARCHEIVED_COMMITTES_INIT = "ARCHEIVED_COMMITTES_INIT"
export const ARCHEIVED_COMMITTES_SUCCESS = "ARCHEIVED_COMMITTES_SUCCESS"
export const ARCHEIVED_COMMITTES_FAIL = "ARCHEIVED_COMMITTES_FAIL"

export const ARCHEIVED_GROUPS_INIT = "ARCHEIVED_GROUPS_INIT"
export const ARCHEIVED_GROUPS_SUCCESS = "ARCHEIVED_GROUPS_SUCCESS"
export const ARCHEIVED_GROUPS_FAIL = "ARCHEIVED_GROUPS_FAIL"

export const SEARCH_TODOLIST_INIT = "SEARCH_TODOLIST_INIT"
export const SEARCH_TODOLIST_SUCCESS = "SEARCH_TODOLIST_SUCCESS"
export const SEARCH_TODOLIST_FAIL = "SEARCH_TODOLIST_FAIL"

export const GET_PAYMENT_METHODS_INIT = "GET_PAYMENT_METHODS_INIT"
export const GET_PAYMENT_METHODS_SUCCESS = "GET_PAYMENT_METHODS_SUCCESS"
export const GET_PAYMENT_METHODS_FAIL = "GET_PAYMENT_METHODS_FAIL"

export const SEARCH_PAYMENT_HISTORY_INIT = "SEARCH_PAYMENT_HISTORY_INIT"
export const SEARCH_PAYMENT_HISTORY_SUCCESS = "SEARCH_PAYMENT_HISTORY_SUCCESS"
export const SEARCH_PAYMENT_HISTORY_FAIL = "SEARCH_PAYMENT_HISTORY_FAIL"

export const SEARCH_POLLS_INIT = "SEARCH_POLLS_INIT"
export const SEARCH_POLLS_SUCCESS = "SEARCH_POLLS_SUCCESS"
export const SEARCH_POLLS_FAIL = "SEARCH_POLLS_FAIL"

export const SAVEPOLL_INIT = "SAVEPOLL_INIT"
export const SAVEPOLL_SUCCESS = "SAVEPOLL_SUCCESS"
export const SAVEPOLL_FAIL = "SAVEPOLL_FAIL"

export const GETALLCOMMITESANDGROUPSFORPOLLS_INIT =
  "GETALLCOMMITESANDGROUPSFORPOLLS_INIT"
export const GETALLCOMMITESANDGROUPSFORPOLLS_SUCCESS =
  "GETALLCOMMITESANDGROUPSFORPOLLS_SUCCESS"
export const GETALLCOMMITESANDGROUPSFORPOLLS_FAIL =
  "GETALLCOMMITESANDGROUPSFORPOLLS_FAIL"

export const RENAMEFOLDER_INIT = "RENAMEFOLDER_INIT"
export const RENAMEFOLDER_SUCCESS = "RENAMEFOLDER_SUCCESS"
export const RENAMEFOLDER_FAIL = "RENAMEFOLDER_FAIL"

export const CREATE_POOL_MODAL = "CREATE_POOL_MODAL"
export const LOADDER_STATE = "LOADDER_STATE"
export const EDIT_POLL_MODAL = "EDIT_POLL_MODAL"
export const GLOBAL_FLAG = "GLOBAL_FLAG"

export const CAST_VOTE_INIT = "CAST_VOTE_INIT"
export const CAST_VOTE_SUCCESS = "CAST_VOTE_SUCCESS"
export const CAST_VOTE_FAIL = "CAST_VOTE_FAIL"

export const RENAMEFILE_INIT = "RENAMEFILE_INIT"
export const RENAMEFILE_SUCCESS = "RENAMEFILE_SUCCESS"
export const RENAMEFILE_FAIL = "RENAMEFILE_FAIL"

export const GETSUBSCRIPTIONDETAIL_INIT = "GETSUBSCRIPTIONDETAIL_INIT"
export const GETSUBSCRIPTIONDETAIL_SUCCESS = "GETSUBSCRIPTIONDETAIL_SUCCESS"
export const GETSUBSCRIPTIONDETAIL_FAIL = "GETSUBSCRIPTIONDETAIL_FAIL"

export const GETSUBSCRIPTIONUPGRADEAMOUNTDETAIL_INIT =
  "GETSUBSCRIPTIONUPGRADEAMOUNTDETAIL_INIT"
export const GETSUBSCRIPTIONUPGRADEAMOUNTDETAIL_SUCCESS =
  "GETSUBSCRIPTIONUPGRADEAMOUNTDETAIL_SUCCESS"
export const GETSUBSCRIPTIONUPGRADEAMOUNTDETAIL_FAIL =
  "GETSUBSCRIPTIONUPGRADEAMOUNTDETAIL_FAIL"

export const GETSUBSCRIPTIONUPGRADEPAYMENTCOMPLETE_INIT =
  "GETSUBSCRIPTIONUPGRADEPAYMENTCOMPLETE_INIT"
export const GETSUBSCRIPTIONUPGRADEPAYMENTCOMPLETE_SUCCESS =
  "GETSUBSCRIPTIONUPGRADEPAYMENTCOMPLETE_SUCCESS"
export const GETSUBSCRIPTIONUPGRADEPAYMENTCOMPLETE_FAIL =
  "GETSUBSCRIPTIONUPGRADEPAYMENTCOMPLETE_FAIL"

export const PAYMENTCOMPLETE_INIT = "PAYMENTCOMPLETE_INIT"
export const PAYMENTCOMPLETE_SUCCESS = "PAYMENTCOMPLETE_SUCCESS"
export const PAYMENTCOMPLETE_FAIL = "PAYMENTCOMPLETE_FAIL"

export const GET_ALL_POLL_STATUS_INIT = "GET_ALL_POLL_STATUS_INIT"
export const GET_ALL_POLL_STATUS_SUCCESS = "GET_ALL_POLL_STATUS_SUCCESS"
export const GET_ALL_POLL_STATUS_FAILED = "GET_ALL_POLL_STATUS_FAILED"

export const GET_POLLS_BY_POLLID_INIT = "GET_POLLS_BY_POLLID_INIT"
export const GET_POLLS_BY_POLLID_SUCCESS = "GET_POLLS_BY_POLLID_SUCCESS"
export const GET_POLLS_BY_POLLID_FAILED = "GET_POLLS_BY_POLLID_FAILED"

export const UPDATE_POLLS_INIT = "UPDATE_POLLS_INIT"
export const UPDATE_POLLS_SUCCESS = "UPDATE_POLLS_SUCCESS"
export const UPDATE_POLLS_FAILED = "UPDATE_POLLS_FAILED"

export const VIEW_POLL_MODAL = "VIEW_POLL_MODAL"

export const VOTE_POLL_MODAL = "VOTE_POLL_MODAL"

export const VIEW_POLL_PROGRESS = "VIEW_POLL_PROGRESS"

export const VIEW_VOTES_DETAILS = "VIEW_VOTES_DETAILS"

export const VIEW_VOTES_INIT = "VIEW_VOTES_INIT"
export const VIEW_VOTES_SUCCESS = "VIEW_VOTES_SUCCESS"
export const VIEW_VOTES_FAILED = "VIEW_VOTES_FAILED"

export const DELETE_POLL_MODAL = "DELETE_POLL_MODAL"

//NEW MEETING STATES
export const NEW_MEETING_ADDUSER_MODAL = "NEW_MEETING_ADDUSER_MODAL"
export const CROSS_CONFIRMATION_MODAL = "CROSS_CONFIRMATION_MODAL "
export const NOTIFY_ORGANIZORS_MODAL = "NOTIFY_ORGANIZORS_MODAL"

export const ADD_AGENDA_CONTRIBUTORS = "ADD_AGENDA_CONTRIBUTORS"
export const NOTIFY_AGENDA_CONTRIBUTORS = "NOTIFY_AGENDA_CONTRIBUTORS"
export const ADD_PARTICIPANTS_MODAL = "ADD_PARTICIPANTS_MODAL"
export const AGENDA_ITEM_REMOVED = "AGENDA_ITEM_REMOVED"
export const MAIN_AGENDA_ITEM_REMOVED = "MAIN_AGENDA_ITEM_REMOVED"
export const ADVANCED_PERSMISSION_MODAL = "ADVANCED_PERSMISSION_MODAL"

export const DELETE_POLL_INIT = "DELETE_POLL_INIT"
export const DELETE_POLL_SUCCESS = "DELETE_POLL_SUCCESS"
export const DELETE_POLL_FAILED = "DELETE_POLL_FAILED"

export const UPDATE_MESSAGE_ACKNOWLEDGEMENT_INIT =
  "UPDATE_MESSAGE_ACKNOWLEDGEMENT_INIT"
export const UPDATE_MESSAGE_ACKNOWLEDGEMENT_SUCCESS =
  "UPDATE_MESSAGE_ACKNOWLEDGEMENT_SUCCESS"
export const UPDATE_MESSAGE_ACKNOWLEDGEMENT_FAIL =
  "UPDATE_MESSAGE_ACKNOWLEDGEMENT_FAIL"

export const GROUP_LOADER_STATE = "GROUP_LOADER_STATE"

//CHAT FILTER ACTION TYPES
export const RECENT_CHAT_FLAG = "RECENT_CHAT_FLAG"
export const PRIVATE_CHAT_FLAG = "PRIVATE_CHAT_FLAG"
export const PRIVATE_GROUPS_CHAT_FLAG = "PRIVATE_GROUPS_CHAT_FLAG"
export const STARRED_MESSAGE_FLAG = "STARRED_MESSAGE_FLAG"
export const BLOCKED_USERS_FLAG = "BLOCKED_USERS_FLAG"
export const SHOUTALL_CHAT_FLAG = "SHOUTALL_CHAT_FLAG"
export const DELETE_CHAT_FLAG = "DELETE_CHAT_FLAG"

//Header Footer
export const HEADER_SHOW_HIDE_STATUS = "HEADER_SHOW_HIDE_STATUS"
export const FOOTER_SHOW_HIDE_STATUS = "FOOTER_SHOW_HIDE_STATUS"
export const FOOTER_ACTION_STATUS = "FOOTER_ACTION_STATUS"

//Security Encryption
export const SECURITY_ENCRYPTION_STATUS = "SECURITY_ENCRYPTION_STATUS"

//Footer Feature Reducers
export const ADD_NEW_CHAT_SCREEN = "ADD_NEW_CHAT_SCREEN"
export const CREATE_GROUP_SCREEN = "CREATE_GROUP_SCREEN"
export const CREATE_SHOUTALL_SCREEN = "CREATE_SHOUTALL_SCREEN"

export const CHATBOX_ACTIVE_FLAG = "CHATBOX_ACTIVE_FLAG"

export const GET_ACTIVE_CHAT = "GET_ACTIVE_CHAT"

export const CHAT_MESSAGE_SEARCH = "CHAT_MESSAGE_SEARCH"

export const SAVE_MODAL_FLAG = "SAVE_MODAL_FLAG"
export const PRINT_MODAL_FLAG = "PRINT_MODAL_FLAG"
export const EMAIL_MODAL_FLAG = "EMAIL_MODAL_FLAG"

export const PUSH_MESSAGE_DATA = "PUSH_MESSAGE_DATA"

export const PUSH_CHAT_DATA = "PUSH_CHAT_DATA"

export const FILE_UPLOAD_FLAG = "FILE_UPLOAD_FLAG"
export const FILE_UPLOAD_DATA = "FILE_UPLOAD_DATA"

export const ACTIVE_MESSAGE_DATA = "ACTIVE_MESSAGE_DATA"

export const GET_ALL_STARRED_MESSAGES_INIT = "GET_ALL_STARRED_MESSAGES_INIT"
export const GET_ALL_STARRED_MESSAGES_SUCCESS =
  "GET_ALL_STARRED_MESSAGES_SUCCESS"
export const GET_ALL_STARRED_MESSAGES_FAIL = "GET_ALL_STARRED_MESSAGES_FAIL"

export const CHATS_SEARCH_FLAG = "CHATS_SEARCH_FLAG"

export const MQTT_MESSAGE_DELETED = "MQTT_MESSAGE_DELETED"
export const DOWNLOAD_CHAT_EMPTY = "DOWNLOAD_CHAT_EMPTY"

export const GET_ALL_MESSAGES_INIT = "GET_ALL_MESSAGES_INIT"
export const GET_ALL_MESSAGES_SUCCESS = "GET_ALL_MESSAGES_SUCCESS"
export const GET_ALL_MESSAGES_FAIL = "GET_ALL_MESSAGES_FAIL"

export const RESET_CLOSE_CHAT_FLAGS = "RESET_CLOSE_CHAT_FLAGS"

export const EMAIL_CHAT_INIT = "EMAIL_CHAT_INIT"
export const EMAIL_CHAT_SUCCESS = "EMAIL_CHAT_SUCCESS"
export const EMAIL_CHAT_FAIL = "EMAIL_CHAT_FAIL"
export const MQTT_MESSAGE_STATUS_UPDATE = "MQTT_MESSAGE_STATUS_UPDATE"
export const ALL_POLLINGS_SOCKET = "ALL_POLLINGS_SOCKET"

export const CREATE_RESOLUTION_MODAL = "CREATE_RESOLUTION_MODAL"
export const UPDATE_RESOLUTION_MODAL = "UPDATE_RESOLUTION_MODAL"
export const VIEW_RESOLUTION_MODAL = "VIEW_RESOLUTION_MODAL"

//Video Action Types
export const CONTACT_VIDEO_FLAG = "CONTACT_VIDEO_FLAG"
export const RECENT_VIDEO_FLAG = "RECENT_VIDEO_FLAG"
export const VIDEO_CHAT_SEARCH_FLAG = "VIDEO_CHAT_SEARCH_FLAG"
export const VIDEO_CHAT_FLAG = "VIDEO_CHAT_FLAG"

export const VIDEO_CALL_OTO_FLAG = "VIDEO_CALL_OTO_FLAG"
export const VIDEO_CALL_GROUP_FLAG = "VIDEO_CALL_GROUP_FLAG"
export const VIDEO_CALL_NORMAL_SCREEN_FLAG = "VIDEO_CALL_NORMAL_SCREEN_FLAG"
export const VIDEO_CALL_MINIMIZE_SCREEN_FLAG = "VIDEO_CALL_MINIMIZE_SCREEN_FLAG"
export const VIDEO_CALL_MAXIMIZE_SCREEN_FLAG = "VIDEO_CALL_MAXIMIZE_SCREEN_FLAG"
export const END_VIDEO_CALL_FLAG = "END_VIDEO_CALL_FLAG"
export const VIDEO_CALL_NORMAL_HEADER_FLAG = "VIDEO_CALL_NORMAL_HEADER_FLAG"
export const VIDEO_CALL_MINIMIZE_HEADER_FLAG = "VIDEO_CALL_MINIMIZE_HEADER_FLAG"
export const VIDEO_CALL_MAXIMIZE_HEADER_FLAG = "VIDEO_CALL_MAXIMIZE_HEADER_FLAG"
export const VIDEO_INCOMING_CALL_MAX = "VIDEO_INCOMING_CALL_MAX"
export const CHAT_ENABLE_NORMAL_FLAG = "CHAT_ENABLE_NORMAL_FLAG"
export const AGENDA_ENABLE_NORMAL_FLAG = "AGENDA_ENABLE_NORMAL_FLAG"
export const MINUTES_MEETING_ENABLE_NORMAL_FLAG =
  "MINUTES_MEETING_ENABLE_NORMAL_FLAG"
export const VIDEO_OUTGOING_CALL_MAX = "VIDEO_OUTGOING_CALL_MAX"
export const VIDEO_MULTIPLE_CALL_MAX = "VIDEO_MULTIPLE_CALL_MAX"
export const VIDEO_MAX_CHAT_OPEN = "VIDEO_MAX_CHAT_OPEN"
export const VIDEO_MAX_AGENDA_OPEN = "VIDEO_MAX_AGENDA_OPEN"
export const VIDEO_MAX_MINUTES_OPEN = "VIDEO_MAX_MINUTES_OPEN"
export const MINIMIZE_VIDEO_PANEL = "MINIMIZE_VIDEO_PANEL"
export const NORMALIZE_VIDEO_PANEL = "NORMALIZE_VIDEO_PANEL"
export const MAXIMIZE_VIDEO_PANEL = "MAXIMIZE_VIDEO_PANEL"

export const ADVANCE_PERMISSION_CONFIRMATION = "ADVANCE_PERMISSION_CONFIRMATION"

export const CREATE_FOLDER_SUCCESS = "CREATE_FOLDER_SUCCESS"

export const SAVEFILESANDFOLDERS_INIT = "SAVEFILESANDFOLDERS_INIT"
export const SAVEFILESANDFOLDERS_SUCCESS = "SAVEFILESANDFOLDERS_SUCCESS"
export const SAVEFILESANDFOLDERS_FAIL = "SAVEFILESANDFOLDERS_FAIL"

export const VOTE_AGENDA_MODAL = "VOTE_AGENDA_MODAL"

export const VOTE_MODAL_CONFIRMATION = "VOTE_MODAL_CONFIRMATION"

export const IMPORT_PREVIOUS_AGENDA = "IMPORT_PREVIOUS_AGENDA"

export const DELETE_TODO_COMMENT_INIT = "DELETE_TODO_COMMENT_INIT"
export const DELETE_TODO_COMMENT_SUCCESS = "DELETE_TODO_COMMENT_SUCCESS"
export const DELETE_TODO_COMMENT_FAIL = "DELETE_TODO_COMMENT_FAIL"

export const DATAROOM_TABLE_SCROLL_BAR = "DATAROOM_TABLE_SCROLL_BAR"

export const INCOMING_VIDEO_FLAG = "INCOMING_VIDEO_FLAG"

export const GET_ALL_LANGUAGES_INITIAL = "GET_ALL_LANGUAGES_INITIAL"
export const GET_ALL_LANGUAGES_SUCCESS = "GET_ALL_LANGUAGES_SUCCESS"
export const GET_ALL_LANGUAGES_FAIL = "GET_ALL_LANGUAGES_FAIL"

export const SET_SELECTED_LANGUAGE_INITIAL = "SET_SELECTED_LANGUAGE_INITIAL"
export const SET_SELECTED_LANGUAGE_SUCCESS = "SET_SELECTED_LANGUAGE_SUCCESS"
export const SET_SELECTED_LANGUAGE_FAIL = "SET_SELECTED_LANGUAGE_FAIL"

//Video Call Action Types
export const GET_ALL_VIDEOCALL_USERS_INITIAL = "GET_ALL_VIDEOCALL_USERS_INITIAL"
export const GET_ALL_VIDEOCALL_USERS_SUCCESS = "GET_ALL_VIDEOCALL_USERS_SUCCESS"
export const GET_ALL_VIDEOCALL_USERS_FAIL = "GET_ALL_VIDEOCALL_USERS_FAIL"

export const INITIATE_VIDEO_CALL_INITIAL = "INITIATE_VIDEO_CALL_INITIAL"
export const INITIATE_VIDEO_CALL_SUCCESS = "INITIATE_VIDEO_CALL_SUCCESS"
export const INITIATE_VIDEO_CALL_FAIL = "INITIATE_VIDEO_CALL_FAIL"

export const INCOMING_VIDEO_CALL_MQTT = "INCOMING_VIDEO_CALL_MQTT"

export const DATAROOM_DATA_BEHAVIOUR = "DATAROOM_DATA_BEHAVIOUR"

export const IMPORT_PREVIOUS_MINUTES = "IMPORT_PREVIOUS_MINUTES"

export const AFTER_IMPORT_STATE = "AFTER_IMPORT_STATE"

export const NEW_RESOLUTION_CREATED_MQTT = "NEW_RESOLUTION_CREATED_MQTT"

export const CLOSED_RESOLUTION_MQTT = "CLOSED_RESOLUTION_MQTT"

export const CANCELLED_RESOLUTION_MQTT = "CANCELLED_RESOLUTION_MQTT"

export const VIDEO_CALL_RESPONSE_INITIAL = "VIDEO_CALL_RESPONSE_INITIAL"
export const VIDEO_CALL_RESPONSE_SUCCESS = "VIDEO_CALL_RESPONSE_SUCCESS"
export const VIDEO_CALL_RESPONSE_FAIL = "VIDEO_CALL_RESPONSE_FAIL"

export const GET_VIDEO_RECIPENT_DATA = "GET_VIDEO_RECIPENT_DATA"

export const INCOMING_VIDEO_CALL_ACCEPTED_MQTT =
  "INCOMING_VIDEO_CALL_ACCEPTED_MQTT"

export const GET_SELECTED_LANGUAGE_INITIAL = "GET_SELECTED_LANGUAGE_INITIAL"
export const GET_SELECTED_LANGUAGE_SUCCESS = "GET_SELECTED_LANGUAGE_SUCCESS"
export const GET_SELECTED_LANGUAGE_FAIL = "GET_SELECTED_LANGUAGE_FAIL"

export const ENABLE_PROPOSED_MEETING_DATE = "ENABLE_PROPOSED_MEETING_DATE"

export const PROPOSED_MEETING_SAVED_MODAL = "PROPOSED_MEETING_SAVED_MODAL"

export const GET_ALL_RECENTCALLS_INITIAL = "GET_ALL_RECENTCALLS_INITIAL"
export const GET_ALL_RECENTCALLS_SUCCESS = "GET_ALL_RECENTCALLS_SUCCESS"
export const GET_ALL_RECENTCALLS_FAIL = "GET_ALL_RECENTCALLS_FAIL"

export const UNSAVE_MINUTES_FILEUPLOAD = "UNSAVE_MINUTES_FILEUPLOAD"
export const UPDATE_PROFILE_PICTURE_INIT = "UPDATE_PROFILE_PICTURE_INIT"
export const UPDATE_PROFILE_PICTURE_SUCCESS = "UPDATE_PROFILE_PICTURE_SUCCESS"
export const UPDATE_PROFILE_PICTURE_FAIL = "UPDATE_PROFILE_PICTURE_FAIL"

export const ISFOLDER = "ISFOLDER"
export const FOLDER_UPLOAD_DATA = "FOLDER_UPLOAD_DATA"

export const CALL_REQUEST_RECEIVED_INITIAL = "CALL_REQUEST_RECEIVED_INITIAL"
export const CALL_REQUEST_RECEIVED_SUCCESS = "CALL_REQUEST_RECEIVED_SUCCESS"
export const CALL_REQUEST_RECEIVED_FAIL = "CALL_REQUEST_RECEIVED_FAIL"
export const CALL_REQUEST_RECEIVED_MQTT = "CALL_REQUEST_RECEIVED_MQTT"

export const UNSAVED_CREATE_FROM_SCRATCH = "UNSAVED_CREATE_FROM_SCRATCH"
export const UNSAVED_BUTTON_CREATE_SCRATCH = "UNSAVED_BUTTON_CREATE_SCRATCH"
export const UNSAVED_IMPORT_AGENDA = "UNSAVED_IMPORT_AGENDA"
export const GET_MISSED_CALL_COUNT_INITIAL = "GET_MISSED_CALL_COUNT_INITIAL"
export const GET_MISSED_CALL_COUNT_SUCCESS = "GET_MISSED_CALL_COUNT_SUCCESS"
export const GET_MISSED_CALL_COUNT_FAIL = "GET_MISSED_CALL_COUNT_FAIL"

export const SCROLL_BEHAVIOR_SPINNER = "SCROLL_BEHAVIOR_SPINNER"

export const LEAVE_CALL_MODAL = "LEAVE_CALL_MODAL"

export const LEAVE_CALL_ACTION = "LEAVE_CALL_ACTION"

export const MISSED_CALL_COUNT_MQTT = "MISSED_CALL_COUNT_MQTT"

export const REMOVE_FOLDER_UPLOAD_DATA = "REMOVE_FOLDER_UPLOAD_DATA"

export const UNSAVED_MODAL_ACTIONS = "UNSAVED_MODAL_ACTIONS"

export const REMOVED_TABLE_MODAL = "REMOVED_TABLE_MODALS"

export const DELETE_TODO_COMMENT_ID = "DELETE_TODO_COMMENT_ID"
