//For Authentication api's

//for signup
export const SIGN_UP_INIT = "SIGN_UP_INIT";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

//for login
export const SIGN_IN_INIT = "SIGN_IN_INIT";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAIL = "SIGN_IN_FAIL";

//for forgot password
export const FORGOT_PASSWORD_INIT = "FORGOTPASSWORD_IN_INIT";
export const FORGOT_PASSWORD_SUCCESS = "FORGOTPASSWORD_IN_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOTPASSWORD_IN_FAIL";

//for opt verification
export const VERIFY_OPT_INIT = "VERIFY_IN_INIT";
export const VERIFY_OPT_SUCCESS = "VERIFY_OPT_SUCCESS";
export const VERIFY_OPT_FAIL = "VERIFY_OPT_FAIL";

export const VERIFY_OTPSIGNUP_SUCCESS = "VERIFY_OTPSIGNUP_SUCCESS";
export const VERIFY_OTPSIGNUP_FAIL = "VERIFY_OTPSIGNUP_FAIL";

export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";
export const RESEND_OTP_FAIL = "RESEND_OTP_FAIL";

export const RESEND_OTP_FORGOTPASSWORD_SUCCESS =
  "RESEND_OTP_FORGOTPASSWORD_SUCCESS";
export const RESEND_OTP_FORGOTPASSWORD_FAIL = "RESEND_OTP_FORGOTPASSWORD_FAIL";

// for change password
export const CHANGE_PASSWORD_INIT = "CHANGE_PASSWORD_INIT";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL";

//for signout
export const SIGN_OUT = "SIGN_OUT";

//Refresh token
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAIL = "REFRESH_TOKEN_FAIL";

//Clear State Back Button
export const CLEAR_STATE_BACK = "CLEAR_STATE_BACK";

//TodoList
export const SHOW = "SHOW";
export const SET_LOADER_FALSE = "SET_LOADER_FALSE";
export const GET_TODOLIST_LOADER_START = "GET_TODOLIST_LOADER_START";
export const GET_TODO_FAIL = "GET_TODO_FAIL";

//Upload
export const GET_UPLOAD_FAIL = "GET_UPLOAD_FAIL";
export const GET_UPLOAD_LOADER_START = "GET_UPLOAD_LOADER_START";
export const SET_LOADER_FALSE_UPLOAD = "SET_LOADER_FALSE_UPLOAD";
export const UPLOAD_DOCUMNET_FILE_SUCCESS = "UPLOAD_DOCUMNET_FILE_SUCCESS";
export const UPLOAD_DOCUMNET_FILE_FAIL = "UPLOAD_DOCUMNET_FILE_FAIL";
export const GET_ALL_ASSIGNEES_SUCCESS = "GET_ALL_ASSIGNEES_SUCCESS";
export const GET_ALL_ASSIGNEES_FAIL = "GET_ALL_ASSIGNEES_FAIL";

// ali
//for Gell All Settings
export const GETSETTING_INIT = "SETTINGS_INIT";
export const GETSETTING_SUCCESS = "SETTING_SUCCESS";
export const GETSETTING_FAIL = "SETTING_FAIL";

//FOR UPDATE USER PROFILE
export const UPDATEUSERPROFILE_INIT = "UPDATEUSERPROFILE_INIT";
export const UPDATEUSERPROFILE_SUCCESS = "UPDATEUSERPROFILE_SUCCESS";
export const UPDATEUSERPROFILE_FAIL = "UPDATEUSERPROFILE_FAIL";

// FOR UPDATE USER NOTIFCATION
export const UPDATEUSERNOTIFICATION_INIT = "UPDATEUSERNOTIFICATION_INIT";
export const UPDATEUSERNOTIFICATION_SUCCESS = "UPDATEUSERNOTIFICATION_SUCCESS";
export const UPDATEUSERNOTIFICATION_FAIL = "UPDATEUSERNOTIFICATION_FAIL";

//FOR UPDATE USER GENERAL SETTING
export const UPDATEUSERGENERALSETTING_INIT = "UPDATEUSERGENERALSETTING_INIT";
export const UPDATEUSERGENERALSETTING_SUCCESS =
  "UPDATEUSERGENERALSETTING_SUCCESS";
export const UPDATEUSERGENERALSETTING_FAIL = "UPDATEUSERGENERALSETTING_FAIL";

//FOR GETTING USER NOTIFICATION
export const GETUSERNOTIFICATION_INIT = "GETUSERNOTIFICATION_INIT";
export const GETUSERNOTIFICATION_SUCCESS = "GETUSERNOTIFICATION_SUCCESS";
export const GETUSERNOTIFICATION_FAIL = "GETUSERNOTIFICATION_FAIL";
// aun
//For FAQ's
export const GET_FAQS_INIT = "GET_FAQS_INIT";
export const GET_FAQS_SUCCESS = "GET_FAQS_SUCCESS";
export const GET_FAQS_FAIL = "GET_FAQS_FAIL";

// For COUNTRY CODES
export const GET_COUNTRYCODE_INIT = "GET_COUNTRYCODE_INIT";
export const GET_COUNTRYCODE_SUCCESS = "GET_COUNTRYCODE_SUCCESS";
export const GET_COUNTRYCODE_FAIL = "GET_COUNTRYCODE_FAIL";

// FOR TIME ZONES
export const GET_TIMEZONE_INIT = "GET_TIMEZONE_INIT";
export const GET_TIMEZONE_SUCCESS = "GET_TIMEZONE_SUCCESS";
export const GET_TIMEZONE_FAIL = "GET_TIMEZONE_FAIL";

//aun
//For GetMeetingByUserID
export const GET_MEETINGUSERID_INIT = "GET_MEETINGUSERID_INIT";
export const GET_MEETINGUSERID_SUCCESS = "GET_MEETINGUSERID_SUCCESS";
export const GET_MEETINGUSERID_FAIL = "GET_MEETINGUSERID_FAIL";
export const SEARCH_MEETING_RESPONSE = "SEARCH_MEETING_RESPONSE";

//aun
//Get todolist User id
export const GET_TODOLIST_INIT = " GET_TODOLIST_INIT";
export const GET_TODOLIST_SUCCESS = " GET_TODOLIST_SUCCESS";
export const GET_TODOLIST_FAIL = " GET_TODOLIST_FAIL";

// FOR ASSIGNEES LIST
export const ASSIGNESS_LIST_INIT = "ASSIGNESS_LIST_INIT";
export const ASSIGNESS_LIST_SUCCESS = "ASSIGNESS_LIST_SUCCESS";
export const ASSIGNESS_LIST_FAIL = "ASSIGNESS_LIST_FAIL";

//SCHEDULE MEETING
export const SCHEDULE_NEW_MEETING_INIT = "SCHEDULE_NEW_MEETING_INIT";
export const SCHEDULE_NEW_MEETING_FAIL = "SCHEDULE_NEW_MEETING_FAIL";

//VIEW MEETING
export const VIEW_MEETING_INIT = "VIEW_MEETING_INIT";
export const VIEW_MEETING_SUCESS = "VIEW_MEETING_SUCESS";
export const VIEW_MEETING_FAIL = "VIEW_MEETING_FAIL";

// CLEARE STATE OF ASSIGNEES LIST STATES
export const CLEARE_STATE = "CLEARE_STATE";
export const VIEW_TODO_SUCCESS = "VIEW_TODO_SUCCESS";
export const VIEW_TODO_FAIL = "VIEW_TODO_FAIL";

export const CLEAR_STATE = "CLEAR_STATE";
export const CLEAR_RESPONSE_MESSAGE = "CLEAR_RESPONSE_MESSAGE";

export const CANCEL_MEETING_INIT = "CANCEL_MEETING_INIT";
export const CANCEL_MEETING_SUCCESS = "CANCEL_MEETING_SUCCESS";
export const CANCEL_MEETING_FAIL = "CANCEL_MEETING_FAIL";

export const START_MEETING_INIT = "START_MEETING_INIT";
export const START_MEETING_SUCCESS = "START_MEETING_SUCCESS";
export const START_MEETING_FAIL = "START_MEETING_FAIL";

export const END_MEETING_INIT = "END_MEETING_INIT";
export const END_MEETING_SUCCESS = "END_MEETING_SUCCESS";
export const END_MEETING_FAIL = "END_MEETING_FAIL";

// GET CALENDAR DATA
export const GET_DATA_FOR_CALENDAR_INIT = "GET_DATA_FOR_CALENDAR_INIT";
export const GET_DATA_FOR_CALENDAR_SUCCESS = "GET_DATA_FOR_CALENDAR_SUCCESS";
export const GET_DATA_FOR_CALENDAR_FAIL = "GET_DATA_FOR_CALENDAR_FAIL";

// MAINTAIN STATES FOR ONBOARDS

export const SHOW_MODAL_STATE = "SHOW_MODAL_STATE";
export const ISDETAIL_MODAL_STATE = "ISDETAIL_MODAL_STATE";
export const ISAGENDA_MODAL_STATE = "ISAGENDA_MODAL_STATE";
export const ISATTENDEES_MODAL_STATE = "ISATTENDEES_MODAL_STATE";
export const STEPS_MODAL_STATE = "STEPS_MODAL_STATE";

// GET TODOS STATUS
export const GET_TODOSSTATUS_INIT = "GET_TODOSSTATUS_INIT";
export const GET_TODOSSTATUS_SUCCESS = "GET_TODOSSTATUS_SUCCESS";
export const GET_TODOSSTATUS_FAIL = "GET_TODOSSTATUS_FAIL";

// UPDATE TODOS STATUS
export const UPDATE_TODOSTATUS_INIT = "UPDATE_TODOSTATUS_INIT";
export const UPDATE_TODOSTATUS_SUCCESS = "UPDATE_TODOSTATUS_SUCCESS";
export const UPDATE_TODOSTATUS_FAIL = "UPDATE_TODOSTATUS_FAIL";

//Download
export const GET_DOWNLOAD_FAIL = "GET_DOWNLOAD_FAIL";
export const GET_DOWNLOAD_LOADER_START = "GET_DOWNLOAD_LOADER_START";
export const SET_LOADER_FALSE_DOWNLOAD = "SET_LOADER_FALSE_DOWNLOAD";
export const DOWNLOAD_DOCUMENT_FILE_SUCCESS = "DOWNLOAD_DOCUMENT_FILE_SUCCESS";
export const DOWNLOAD_DOCUMENT_FILE_FAIL = "DOWNLOAD_DOCUMENT_FILE_FAIL";

export const RESET_ALL_FILES_UPLOAD = "RESET_ALL_FILES_UPLOAD";

// POST ASSGINEEE COMMENTS IN TODOVIEW
export const POST_ASSIGNEEECOMMENTS_INIT = "POST_ASSIGNEEECOMMENTS_INIT";
export const POST_ASSIGNEEECOMMENTS_SUCCESS = "POST_ASSIGNEEECOMMENTS_SUCCESS";
export const POST_ASSIGNEEECOMMENTS_FAIL = "POST_ASSIGNEEECOMMENTS_FAIL";

export const SET_LOADER_TRUE = "SET_LOADER_TRUE";

export const GET_MEETINGCOUNT_SUCCESS = "GET_MEETINGCOUNT_SUCCESS";
export const GET_MEETINGCOUNT_FAIL = "GET_MEETINGCOUNT_FAIL";

export const GET_UPCOMINGEVENTS_SUCCESS = "GET_UPCOMINGEVENTS_SUCCESS";
export const GET_UPCOMINGEVENTS_FAIL = "GET_UPCOMINGEVENTS_FAIL";

export const GET_TODOCOUNT_SUCCESS = "GET_TODOCOUNT_SUCCESS";
export const GET_TODOCOUNT_FAIL = "GET_TODOCOUNT_FAIL";

export const SET_SPINNER_TRUE = "SET_SPINNER_TRUE";
export const SET_SPINNER_FALSE = "SET_SPINNER_FALSE";

export const SET_TABLESPINNER_FALSE = "SET_TABLESPINNER_FALSE";

export const HIDE = "HIDE";

//SHOW VIDEO CHAT COMPONENTS
export const SHOW_ATTACHMENTS_STATE = "SHOW_ATTACHMENTS_STATE";
export const SHOW_MINUTES_STATE = "SHOW_MINUTES_STATE";

// SHOW HID MEETING AGENDA MODAL IN VIDEO CALL
export const MEETINGATTACHMENT_MODAL = "MEETINGATTACHMENT_MODAL";

// GET MEETING AGENDAS
export const GET_MEETINGAGENDAS_INIT = "GET_MEETINGAGENDAS_INIT";
export const GET_MEETINGAGENDAS_SUCCESS = "GET_MEETINGAGENDAS_SUCCESS";
export const GET_MEETINGAGENDAS_FAIL = "GET_MEETINGAGENDAS_FAIL";

// GET MEEETING ATTACHMENTS
export const GET_ATTACHMENTSBYMEETINGID_INIT =
  "GET_ATTACHMENTSBYMEETINGID_INIT";
export const GET_ATTACHMENTSBYMEETINGID_SUCCESS =
  "GET_ATTACHMENTSBYMEETINGID_SUCCESS";
export const GET_ATTACHMENTSBYMEETINGID_FAIL =
  "GET_ATTACHMENTSBYMEETINGID_FAIL";

// GET AGENDA ATTACHMENT UPDATES
export const AGENDA_ATTACHMENTUPDATE_INIT = "AGENDA_ATTACHMENTUPDATE_INIT";
export const AGENDA_ATTACHMENTUPDATE_SUCCESS =
  "AGENDA_ATTACHMENTUPDATE_SUCCESS";
export const AGENDA_ATTACHMENTUPDATE_FAIL = "AGENDA_ATTACHMENTUPDATE_FAIL";

export const UPDATE_MINUTESOFMEETING_INIT = "UPDATE_MINUTESOFMEETING_INIT";
export const UPDATE_MINUTESOFMEETING_SUCCESS =
  "UPDATE_MINUTESOFMEETING_SUCCESS";
export const UPDATE_MINUTESOFMEETING_FAIL = "UPDATE_MINUTESOFMEETING_FAIL";

export const ADD_MINUTESOFMEETING_INIT = "UPDATE_MINUTESOFMEETING_INIT";
export const ADD_MINUTESOFMEETING_SUCCESS = "UPDATE_MINUTESOFMEETING_SUCCESS";
export const ADD_MINUTESOFMEETING_FAIL = "UPDATE_MINUTESOFMEETING_FAIL";
export const HIDEMINUTEMESSAGE = "HIDEMINUTEMESSAGE";

export const GET_REMINDERS_INIT = "GET_REMINDERS_INIT";
export const GET_REMINDERS_SUCCESS = "GET_REMINDERS_SUCCESS";
export const GET_REMINDERS_FAIL = "GET_REMINDERS_FAIL";

export const AUTH_RESPONSE_MESSAGE = "AUTH_RESPONSE_MESSAGE";
export const DOWNLOAD_RESPONSE_MESSAGE = "DOWNLOAD_RESPONSE_MESSAGE";
export const FAQS_RESPONSE_MESSAGE = "FAQS_RESPONSE_MESSAGE";
export const LISTOFASSIGNEE_RESPONSE_MESSAGE =
  "LISTOFASSIGNEE_RESPONSE_MESSAGE";
export const CALENDAR_RESPONSE_MESSAGE = "CALENDAR_RESPONSE_MESSAGE";
export const MEETINGID_RESPONSE_MESSAGE = "MEETINGID_RESPONSE_MESSAGE";
export const TODOS_STATUS_RESPONSE_MESSAGE = "TODOS_STATUS_RESPONSE_MESSAGE";
export const POST_ASSIGNEE_RESPONSE_MESSAGE = "POST_ASSIGNEE_RESPONSE_MESSAGE";
export const SETTING_RESPONSE_MESSAGE = "SETTING_RESPONSE_MESSAGE";
export const TODOLIST_RESPONSE_MESSAGE = "TODOLIST_RESPONSE_MESSAGE";
export const UPLOAD_RESPONSE_MESSAGE = "UPLOAD_RESPONSE_MESSAGE";
export const VIDEOCHAT_RESPONSE_MESSAGE = "VIDEOCHAT_RESPONSE_MESSAGE";

// socket update recentactivity
export const SETRECENTACTIVITYNOTIFICATION = "SETRECENTACTIVITYNOTIFICATION";

// action type for get tododata from socket
export const SETTODO_RECENT_ACTIVITY_DATA = "SETTODO_RECENT_ACTIVITY_DATA";
export const SET_TODO_STATUS_DATA = "SET_TODO_STATUS_DATA";

// socket Meetings
export const ALL_MEETINGS_SOCKET = "ALL_MEETINGS_SOCKET";

// socket meeting status

export const MEETING_STATUS_SOCKET = "MEETING_STATUS_SOCKET";

// For comments Socket
export const POST_COMMENTS = "POST_COMMENTS";



// Aun work on admin action types (START) //

//For Admin AddUser
export const ADMIN_ADDUSER_INIT = "ADMIN_ADDUSER_INIT";
export const ADMIN_ADDUSER_SUCCESS = "ADMIN_ADDUSER_SUCCESS";
export const ADMIN_ADDUSER_FAIL = "ADMIN_ADDUSER_FAIL";

//For Admin AllMeeting
export const ADMIN_ALLMEETING_INIT = "ADMIN_ALLMEETING_INIT";
export const ADMIN_ALLMEETING_SUCCESS = "ADMIN_ALLMEETING_SUCCESS";
export const ADMIN_ALLMEETING_FAIL = "ADMIN_ALLMEETING_FAIL";

//For Admin CancelSub
export const ADMIN_CANCELSUB_INIT = "ADMIN_CANCELSUB_INIT";
export const ADMIN_CANCELSUB_SUCCESS = "ADMIN_CANCELSUB_SUCCESS";
export const ADMIN_CANCELSUB_FAIL = "ADMIN_CANCELSUB_FAIL";

//For Admin CustomerInformation
export const ADMIN_CUSTOMERINFORMATION_INIT = "ADMIN_CUSTOMERINFORMATION_INIT";
export const ADMIN_CUSTOMERINFORMATION_SUCCESS =
  "ADMIN_CUSTOMERINFORMATION_SUCCESS";
export const ADMIN_CUSTOMERINFORMATION_FAIL = "ADMIN_CUSTOMERINFORMATION_FAIL";

//For Admin EditUser
export const ADMIN_EDITUSER_INIT = "ADMIN_EDITUSER_INIT";
export const ADMIN_EDITUSER_SUCCESS = "ADMIN_EDITUSER_SUCCESS";
export const ADMIN_EDITUSER_FAIL = "ADMIN_EDITUSER_FAIL";

//For Admin Invoice
export const ADMIN_INVOICE_INIT = "ADMIN_INVOICE_INIT";
export const ADMIN_INVOICE_SUCCESS = "ADMIN_INVOICE_SUCCESS";
export const ADMIN_INVOICE_FAIL = "ADMIN_INVOICE_FAIL";

//For Admin Organization
export const ADMIN_ORGANIZATION_INIT = "ADMIN_ORGANIZATION_INIT";
export const ADMIN_ORGANIZATION_SUCCESS = "ADMIN_ORGANIZATION_SUCCESS";
export const ADMIN_ORGANIZATION_FAIL = "ADMIN_ORGANIZATION_FAIL";

//For Admin PackageDetail
export const ADMIN_PACKAGEDETAIL_INIT = "ADMIN_PACKAGEDETAIL_INIT";
export const ADMIN_PACKAGEDETAIL_SUCCESS = "ADMIN_PACKAGEDETAIL_SUCCESS";
export const ADMIN_PACKAGEDETAIL_FAIL = "ADMIN_PACKAGEDETAIL_FAIL";

//For Admin PackageUpgrade
export const ADMIN_PACKAGEUPGRADE_INIT = "ADMIN_PACKAGEUPGRADE_INIT";
export const ADMIN_PACKAGEUPGRADE_SUCCESS = "ADMIN_PACKAGEUPGRADE_SUCCESS";
export const ADMIN_PACKAGEUPGRADE_FAIL = "ADMIN_PACKAGEUPGRADE_FAIL";

//For Admin PayOutstanding
export const ADMIN_PAYOUTSTANDING_INIT = "ADMIN_PAYOUTSTANDING_INIT";
export const ADMIN_PAYOUTSTANDING_SUCCESS = "ADMIN_PAYOUTSTANDING_SUCCESS";
export const ADMIN_PAYOUTSTANDING_FAIL = "ADMIN_PAYOUTSTANDING_FAIL";

//For Admin Summary
export const ADMIN_SUMMARY_INIT = "ADMIN_SUMMARY_INIT";
export const ADMIN_SUMMARY_SUCCESS = "ADMIN_SUMMARY_SUCCESS";
export const ADMIN_SUMMARY_FAIL = "ADMIN_SUMMARY_FAIL";


// Aun work on admin action types (END) //

// for organization Sign up

export const COUNTRYNAMES_INIT = "COUNTRYNAMES_INIT"
export const COUNTRYNAMES_SUCCESS = "COUNTRYNAMES_SUCCESS"
export const COUNTRYNAMES_FAIL = "COUNTRYNAMES_FAIL"

export const GETSUBSCRIPTIONPACAKGES_INIT = "GETSUBSCRIPTIONPACAKGES_INIT"
export const GETSUBSCRIPTIONPACAKGES_SUCCESS = "GETSUBSCRIPTIONPACAKGES_SUCCESS"
export const GETSUBSCRIPTIONPACAKGES_FAIL = "GETSUBSCRIPTIONPACAKGES_FAIL"

export const SIGNUPORGANIZATION_INIT = "SIGNUPORGANIZATION_INIT"
export const SIGNUPORGANIZATION_SUCCESS = "SIGNUPORGANIZATION_SUCCESS"
export const SIGNUPORGANIZATION_FAIL = "SIGNUPORGANIZATION_FAIL"